Валидация запросов пользователей
Studio-Yandex-Practicum/lizaalert_backend pull request #152
Opened 2023-09-21 15:11 UTC by ilin-art

2023-10-26 11:29 UTC, ilin-art commented on src/lizaalert/quizzes/views.py
> +        quiz = Quiz.objects.get(lesson=lesson_id)
Но у нас нет такого поля, если поставить lesson_id будет ошибка:
django.core.exceptions.FieldError: Cannot resolve keyword 'lesson_id' into field. Choices are: author, author_id, created_at, deadline, deleted_at, description, duration_minutes, id, in_progress, lesson, passing_score, questions, retries, status, title, updated_at, useranswer

2023-10-30 13:53 UTC, Di0niz requested changes

2023-10-30 13:53 UTC, Di0niz commented on src/lizaalert/quizzes/views.py
> +        user_answer = UserAnswer.objects.filter(user=user, quiz__lesson=lesson_id).order_by("-id").first()
в quiz нет ссылки на lesson, есть ссылка наоборот lesson ссылается на quiz

запрос будет выглядеть как-то так:

```suggestion
        user_answer = UserAnswer.objects.filter(user=user, quiz_id__in=Lesson.objects.filter(id=lesson_id).values('quiz_id')).order_by("-id").first()
```

2023-10-30 13:53 UTC, Di0niz commented on src/lizaalert/quizzes/views.py
> +        user_answer = UserAnswer.objects.filter(user=user, quiz__lesson=lesson_id).order_by("-id").first()
но если на quiz ссылается урок, тогда здесь в модели имеет смысл заменить quiz на lesson, чтобы ответы хранились по уроку (а не по квизу для всех уроков)

2023-11-13 15:18 UTC, Di0niz approved these changes

2023-11-16 13:21 UTC, cosmofactory requested changes

2023-11-16 13:21 UTC, cosmofactory commented on src/lizaalert/quizzes/utils.py
> +def compare_answers(user_answers, quiz):
надо добавить аннотацию к функции

2023-11-16 13:21 UTC, cosmofactory commented on src/lizaalert/quizzes/utils.py
> +        if question is not None:
```suggestion
        if question:
```

2023-11-16 13:21 UTC, cosmofactory commented on src/lizaalert/quizzes/validators.py
> +    answer_id: List[Union[int, str]]
В питоне >= 3.10 можно делать вот так
```suggestion
    answer_id: List[int | str]
```

2023-11-16 13:21 UTC, cosmofactory commented on src/lizaalert/quizzes/views.py
> +class QuizException(APIException):
Названия вроде бы говорят сами за себя, но с аннотациями будет лучше

2023-11-16 13:21 UTC, cosmofactory commented on src/lizaalert/quizzes/views.py
> +                if quiz.retries != 0 and user_answer.retry_count >= quiz.retries:
Тут я не уверен, но...
допустим quiz.retries = 3
Значит у меня есть 3 попытки сдать квиз. 
Но в данном коде если у меня 3я попытка сдать квиз, то "Попытки закончились"?

2023-11-16 13:21 UTC, cosmofactory commented on src/lizaalert/quizzes/views.py
> +        lesson_id = self.kwargs["lesson_id"]
```suggestion
        lesson_id = self.kwargs.get("lesson_id")
```

Если, по каким то причинам в kwargs не будет lesson_id, то все упадет с KeyError

2023-11-16 13:21 UTC, cosmofactory commented on src/lizaalert/quizzes/views.py
> +        lesson_id = self.kwargs["lesson_id"]
То же самое

2023-11-17 23:03 UTC, ilin-art commented on src/lizaalert/quizzes/views.py
> +                if quiz.retries != 0 and user_answer.retry_count >= quiz.retries:
Не, тут получается попытка добавляется уже после этой проверки, на 3ей попытке тут будет число 2, а на 4ой - 3, последняя строка:
`if quiz.retries != 0 and user_answer.retry_count >= quiz.retries:
                    raise CountExpiredException("Попытки закончились")
            except CountExpiredException as e:
                return Response({"message": e.detail}, status=e.status_code)
            retry_count = user_answer.retry_count = user_answer.retry_count + 1`

2023-11-18 10:32 UTC, cosmofactory approved these changes

2023-11-18 10:36 UTC, merged