Навигация по всем урокам курса
Studio-Yandex-Practicum/lizaalert_backend pull request #211
Opened 2023-11-03 09:30 UTC by cosmofactory

Это не законченный PR, пока только изменены модели

2023-11-08 13:25 UTC, Di0niz requested changes

2023-11-08 13:25 UTC, Di0niz commented on src/lizaalert/courses/migrations/0013_auto_20231102_1949.py
> +class Migration(migrations.Migration):
миграции надо обновить (уже есть  0013)

2023-11-08 13:25 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        return [field for field in fields if field != "order_number"]
лучше использовать filter

2023-11-08 13:25 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        return [field for field in fields if field != "order_number"]
одинаковый код лучше вынести в mixin

2023-11-08 13:25 UTC, Di0niz commented on src/lizaalert/courses/models.py
> -        verbose_name="порядковый номер главы", validators=[MinValueValidator(1)], default=1
лучше так оставить: default=1

2023-11-08 13:25 UTC, Di0niz commented on src/lizaalert/courses/signals.py
> +        old_instance = type(instance).objects.get(id=instance.id)
общий код надо вынести в отдельную функцию

2023-11-08 13:25 UTC, Di0niz commented on src/lizaalert/courses/utils.py
> +                        first_lesson.order_number = self.order_number + 10
`10` магическое значение вынести в константу

2023-11-08 13:25 UTC, Di0niz commented on src/tests/test_courses.py
> +    def test_ordering_working_properly(self, user_client):
лучше сделать параметрами

2023-11-13 20:43 UTC, Di0niz requested changes

2023-11-13 20:43 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +    def save(self, *args, **kwargs):
предусмотреть частичное обновление полей

instance.save(update_fields=['id, title'])

2023-11-13 20:43 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        verbose_name="порядковый номер урока", validators=[MinValueValidator(1)], null=True, blank=True
```suggestion
        verbose_name="порядковый номер урока", validators=[MinValueValidator(1)], blank=True
```

2023-11-13 20:43 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +            set_ordering(self, self.chapter.lessons, 10, self.chapter.order_number)
10 превратить в константу

2023-11-13 20:43 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +            set_ordering(self, self.course.chapters, 1000)
1000 в константу

2023-11-13 20:43 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +    def save(self, *args, **kwargs):
чтобы не дублировать, можно вынести в миксин

2023-11-14 09:52 UTC, Di0niz requested changes

2023-11-14 09:52 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +class SaveOrderingMixin(models.Model):
это же тоже касается порядка уроков и глав, лучше объедини миксины

2023-11-14 09:52 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +    def order_queryset(self):
это должно быть в mixin

2023-11-14 09:52 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +    def order_step(self):
это должно быть в миксин

2023-11-14 09:52 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +    @property
это тоже должно быть в миксин

2023-11-14 13:25 UTC, Di0niz requested changes
нужно еще логику перенести в миксин, чтобы не было зависимостей на классы Lesson, Chapter

2023-11-14 13:25 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +class HideOrderNumberMixin:
сделай default order_number и тогда прятать не нужно.

2023-11-14 13:25 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                return None
```suggestion
            if parent := getattr(self, parent_field):
                return getattr(parent, "order_number")
            return None
```

2023-11-14 13:25 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +def order_number_mixin(step, parent_field, name_of_instance):
```suggestion
def order_number_mixin(step, parent_field):
```

2023-11-14 13:25 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +            verbose_name=f"порядковый номер {name_of_instance}", validators=[MinValueValidator(1)], blank=True
```suggestion
            verbose_name="порядковый номер", validators=[MinValueValidator(1)], blank=True
```

2023-11-14 13:25 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +class Chapter(TimeStampedModel, order_number_mixin(CHAPTER_STEP, "course", name_of_instance="главы")):
```suggestion
class Chapter(TimeStampedModel, order_number_mixin(CHAPTER_STEP, "course")):
```

2023-11-14 13:25 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +class Lesson(TimeStampedModel, order_number_mixin(LESSON_STEP, "chapter", name_of_instance="урока")):
```suggestion
class Lesson(TimeStampedModel, order_number_mixin(LESSON_STEP, "chapter")):
```

2023-11-14 13:25 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +            verbose_name=f"порядковый номер {name_of_instance}", validators=[MinValueValidator(1)], blank=True
пусть лучше будет универсальное значение

2023-11-14 13:25 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                super().save(*args, **kwargs)
```suggestion
            super().save(*args, **kwargs)
            if (check_for_update is None) or ("order_number" in check_for_update):
                if self.order_number:
                     set_ordering(self, self.order_queryset, step, self.parent_order)
                else:
                    reset_ordering(self, self.order_queryset, step, self.parent_order)
```

2023-11-14 13:25 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                super().save(*args, **kwargs)
а если у объекта нет id;

лучше завязываться на корректное значение order_number:

- если пустое - то в конец;
- если посередине - то реордер;
- если совпало - то ошибка

2023-11-14 13:25 UTC, Di0niz commented on src/lizaalert/courses/signals.py
> +    old_order_number_getter(instance)
тоже надо в миксин вынести

2023-11-14 13:25 UTC, Di0niz commented on src/lizaalert/courses/utils.py
> +def reset_ordering(self, queryset, order_factor, chapter_order=None):
тоже нужно в миксин вынести

2023-11-14 13:47 UTC, cosmofactory commented on src/lizaalert/courses/mixins.py
> +                return None
AttributeError: 'Course' object has no attribute 'order_number'

2023-11-14 13:54 UTC, cosmofactory commented on src/lizaalert/courses/mixins.py
> +                super().save(*args, **kwargs)
Любое подобное изменение и все валится с ошибками, это выстраданная функция, тут лучше ничего не менять)

2023-11-14 14:29 UTC, cosmofactory commented on src/lizaalert/courses/signals.py
> +    old_order_number_getter(instance)
размещать их тут это в стиле джанго, если переносить в миксин, то больше проблем с импортами для ресивера и не понятно будут ли они так работать
предлагаю оставить здесь

2023-11-14 14:34 UTC, cosmofactory commented on src/lizaalert/courses/mixins.py
> +                return None
`return getattr(getattr(self, parent_field), "order_number", None)`
```suggestion
            try:
                return getattr(getattr(self, parent_field), "order_number")
            except AttributeError:
                return None
```

Вспомнил про более красивое решение, мы же можем сказать getattr вернуть что то, в случае отсутствия аттрибута

2023-11-20 09:01 UTC, Di0niz requested changes

2023-11-20 09:01 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +    pass
укажи raw поля, которые содержат ссылки на модели: Пользователи, Курсы, Главы

2023-11-20 09:01 UTC, Di0niz commented on src/lizaalert/courses/migrations/0014_auto_20231109_2223.py
> +        migrations.RemoveConstraint(
order_number по прежнему должен быть уникальных для пар: глава + урок и курс + глава

2023-11-20 09:01 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                super().save(*args, **kwargs)
давай объединим эти механики?

сейчас получается так:

- если это новый урок, то урок будет добавлен в конец
- если старый, то перестраиваем все уроки

для нового урока:

- возникает двойное редактирование: первый раз урок добавляется в конец, второй раз нужно изменить его и вставить в середину

для старого:

- кажется, что перебираются все уроки

2023-11-20 09:01 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +    def ordered_lessons(self):
порядок уроков должен вычисляться в миксине

например, добавь метод ordered

2023-11-20 09:01 UTC, Di0niz commented on src/lizaalert/courses/models.py
> -        constraints = [
можем ли в миксин перенести такой констрейн?

2023-11-20 09:01 UTC, Di0niz commented on src/lizaalert/courses/signals.py
> +@receiver(pre_save, sender=Chapter)
это декоратор, который регистрирует сигнал, попробуй в миксине зарегистрировать класс

2023-11-20 09:01 UTC, Di0niz commented on src/lizaalert/courses/utils.py
> +def old_order_number_getter(instance):
это должно быть в миксине

2023-11-20 09:01 UTC, Di0niz commented on src/tests/test_courses.py
> +        assert response.json()["chapters"][0]["lessons"][2]["order_number"] == 30
здесь достаточно сравнивать только требуемый порядок уроков

2023-11-20 09:01 UTC, Di0niz commented on src/tests/test_courses.py
> +                assert response.json()["next_lesson_id"] == lesson.id + 1
то что id + 1 это не факт

измени порядок обхода, сделай обход по коллекции:


```suggestion
        lessons = Lesson.objects.all().order_by("id")
        prev_lesson = None
        for number, lesson in enumerate(lessons):
            url = reverse("lessons-detail", kwargs={"pk": lesson.id})
            response = user_client.get(url)
            assert response.status_code == status.HTTP_200_OK
            assert response.json()["prev_lesson_id"] = prev_lesson
            prev_lesson = response.json()["prev_lesson_id"]


        lessons = Lesson.objects.all().order_by("-id")
        next_lesson = None
        for number, lesson in enumerate(lessons):
            url = reverse("lessons-detail", kwargs={"pk": lesson.id})
            response = user_client.get(url)
            assert response.status_code == status.HTTP_200_OK
            assert response.json()["next_lesson_id"] = next_lesson
            next_lesson = response.json()["next_lesson_id"]
```

Соответственно через параметры избавиться от дублирования: достаточно два параметра: ключ сортировки, ключ из json

2023-11-20 09:01 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +            Переустанавливает очередность глав и уроков.
нужно фильтровать, которые хотим переустановить

2023-11-20 09:01 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                super().save(*args, **kwargs)
предлагаю сделать следующий подход (чтобы было одинакового для всех). по сути есть два кейса:

- если order_number = 0, тогда в конец и нужно только вычислить максимальное значение
- если order_number != 0, тогда ожидаем следующее:
   - пользователь указал order_number и мы получаем все значения больше order_number и перерасчитываем только их

2023-11-20 09:01 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +    class SaveOrderingMixin(models.Model):
добавь property: next_order, prev_order - для получения следующего объекта (возвращать как queryset), чтобы потом подтянуть в сериализаторе

2023-11-20 14:35 UTC, cosmofactory commented on src/lizaalert/courses/signals.py
> +@receiver(pre_save, sender=Chapter)
Не, все ломается. 

Давай оставим в том виде, в котором это советует делать Джанго.  Там же еще в apps.py стоит референс на signals.

2023-11-21 14:41 UTC, ilin-art approved these changes
В логику тут я не лез, а особых ошибок не нашел

2023-11-21 14:41 UTC, ilin-art commented on src/tests/test_courses.py
>          print(response.json())
Отладочный print?

2023-11-22 09:41 UTC, Di0niz requested changes

2023-11-22 09:41 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                old_order_number = type(self).objects.get(id=self.id)
здесь получается весь объект, лучше явно указать какое поле будет получено из БД (чтобы не получать все поля - запрос будет легче)

2023-11-22 09:41 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                    rounded_new_order_number = self.order_number
нужно избавить от магического значения

```suggestion
                rounded_new_order_number = self.order_number // order_factor + self.order_number % order_factor 
```

2023-11-22 09:41 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +            else:
в if сделай return, а основной код вытащи из else

2023-11-22 09:41 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                    for position, object in enumerate(objects):
замени на простой цикл while, чтобы избавиться от position + 1  и position + 2, так будет нагляднее

2023-11-22 09:41 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                            objects_to_update.append(object)
везде добавляются объекты для обновления - вынеси из цикла

2023-11-22 09:41 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +            raise WrongMethodException
в миксине не должно быть бизнес-логике, он не должен знать про то, как его планируют использовать

2023-11-22 09:41 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +            if parent_field == "chapter":
в миксине не должно быть бизнес-логике, он не должен знать про то, как его планируют использовать

2023-11-22 09:41 UTC, Di0niz commented on src/tests/test_courses.py
>          print(response.json())
нужно удалить или логировать log.debug

2023-11-22 12:03 UTC, Di0niz requested changes

2023-11-22 12:03 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                        break
```suggestion
                for obj in objects:
                    # переносим все последующие уроки на один шаг вперед
                    if obj.order_number == self.order_number:
                        position += order_factor
                    
                    # если есть окно, заполняем его уроками
                    if position != obj.order_number:
                        obj.order_number = position
                        objects_to_update.append(obj)
                    position += order_factor
```

2023-11-22 12:03 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                modifier_flag = False
признак модификации не нужен

```suggestion
```

2023-11-22 12:03 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                rounded_new_order_number = self.order_number
```suggestion
            if self.order_number % order_factor != 0:
                self.order_number = (self.order_number // order_factor + 1) * order_factor
```

2023-11-22 12:03 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                    elif obj.order_number == rounded_new_order_number:
```suggestion
                    elif obj.order_number == self.order_number:
```

2023-11-22 12:03 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                    self.order_number = max_order_number + order_factor
```suggestion
                if self.order_number > position:
                    self.order_number = position
```

2023-11-22 12:34 UTC, Di0niz approved these changes

2023-11-22 12:40 UTC, merged