Fix bug profile
Studio-Yandex-Practicum/lizaalert_backend pull request #212
Opened 2023-11-03 20:50 UTC by ilin-art

2023-11-08 11:51 UTC, Di0niz requested changes

2023-11-08 11:51 UTC, Di0niz commented on src/lizaalert/users/models.py
> +        return CourseProgressStatus.objects.filter(
это лучше перенести в queryset view функции, чтобы не было запросов в цикле и убрать propery

2023-11-13 15:14 UTC, Di0niz requested changes

2023-11-13 15:14 UTC, Di0niz commented on src/lizaalert/users/views.py
> +        return Response(serializer.data[0])
почему первый? если данных нет, то будет ошикбка.

нужно добавить тесты

2023-11-16 11:59 UTC, cosmofactory commented on src/tests/test_volunteer_profile.py
> +    @pytest.mark.django_db
`@pytest.mark.django_db `
можно не ставить перед каждой функцией, достаточно поставить перед всем классом

```suggestion
   @pytest.mark.django_db(transaction=True)
   class TestVolunteerProfile:
```

2023-11-18 10:29 UTC, cosmofactory approved these changes

2023-11-22 09:43 UTC, Di0niz requested changes

2023-11-22 09:43 UTC, Di0niz commented on src/lizaalert/users/views.py
> +        queryset = Volunteer.objects.annotate(count_pass_course=Count("volunter_courses")).filter(pk=volunteer.pk)
здесь должен быть список курсов, которые они прошли
осталось фильтр добавить

2023-11-27 10:02 UTC, cosmofactory approved these changes

2023-11-27 10:02 UTC, cosmofactory commented on src/lizaalert/users/serializers.py
> +#         return instance
А почему здесь код закомментирован?

2023-11-27 10:02 UTC, cosmofactory commented on src/lizaalert/users/serializers.py
>      @transaction.non_atomic_requests
Non_atomic_requests применяется только к view, а не к методам.

https://docs.djangoproject.com/en/4.2/topics/db/transactions/

https://stackoverflow.com/questions/49903122/django-decorator-transaction-non-atomic-requests-not-working-in-a-viewset-metho

2023-11-27 13:38 UTC, Di0niz approved these changes

2023-11-27 13:38 UTC, Di0niz commented on src/lizaalert/users/serializers.py
> +# class FullNameSerializer(serializers.ModelSerializer):
комментарии нужно удалить

2023-11-27 14:14 UTC, merged