Сделать активным первый урок при записи на курс
Studio-Yandex-Practicum/lizaalert_backend pull request #217
Opened 2023-11-10 11:55 UTC by cosmofactory

2023-11-13 20:46 UTC, Di0niz requested changes

2023-11-13 20:46 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        progress[0].save()
```suggestion
        progress, created = LessonProgressStatus.objects.get_or_create(user=user, lesson=self)
        progress.userlessonprogress = LessonProgressStatus.ProgressStatus.FINISHED
        progress.save()
```

2023-11-13 20:46 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        return f"Lesson {self.lesson.title}: {self.user.username} Progress: {self.get_userlessonprogress_display()}"
не нужно делать дополнительные запросы

```suggestion
        return f"Lesson {self.lesson_id}: {self.user_id} Progress: {self.get_userlessonprogress_display()}"
```

2023-11-14 11:19 UTC, Di0niz requested changes

2023-11-14 11:19 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +            active_lesson = Lesson.objects.filter(
должен учитываться order_number

2023-11-22 09:45 UTC, Di0niz requested changes

2023-11-22 09:45 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        progress.save()
здесь двойная запись, первый раз получаем, второй раз сохраняем. попробуй сделать за одно действие

2023-11-22 09:45 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        return f"Lesson {self.lesson_id}: {self.user_id} Progress: {self.get_userlessonprogress_display()}"
не вижу такой метод в классе

2023-11-22 13:23 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +        return f"Lesson {self.lesson_id}: {self.user_id} Progress: {self.get_userlessonprogress_display()}"
https://docs.djangoproject.com/en/4.2/ref/models/instances/#django.db.models.Model.get_FOO_display

2023-11-27 13:14 UTC, ilin-art approved these changes

2023-11-27 13:35 UTC, Di0niz approved these changes

2023-11-27 13:40 UTC, merged