Добавить первый урок в serializer response после /id/enroll/
Studio-Yandex-Practicum/lizaalert_backend pull request #233
Opened 2023-11-27 15:45 UTC by cosmofactory

Нам следует разделить понятия current_lesson и initial_lesson.

Initial_lesson - property всего курса, всегда вернет самый первый из опубликованных уроков
Current_lesson - Вернет либо урок со статусом active либо initial_lesson

2023-11-27 22:35 UTC, ilin-art approved these changes

2023-11-27 22:35 UTC, ilin-art commented on src/lizaalert/courses/models.py
> +            .first()
Если ни одного урока не будет, то first() вернет None, что может вызывать ошибки в дальнейшем. Может стоит обработать этот момент?

2023-11-27 22:35 UTC, ilin-art commented on src/lizaalert/courses/views.py
> +        return Response({"initial_lesson": serializer.data}, status=status.HTTP_201_CREATED)
Можно добавить проверку, не подписан ли пользователь уже.

2023-12-04 09:27 UTC, Di0niz requested changes

2023-12-04 09:27 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +            .first()
```suggestion
            Lesson.objects.filter(
                chapter__course=self,
                status=Lesson.LessonStatus.PUBLISHED,
            )
            .exclude(id__in=FinishLesson.objects.filter(status_in=("Пройден"), user=request.user)
            .annotate(ordering=F("chapter__order_number") + F("order_number"))
            .order_by("ordering")
            .first()
```

2023-12-04 11:54 UTC, Di0niz requested changes

2023-12-04 11:54 UTC, Di0niz commented on src/tests/test_courses.py
>          assert response_2.json()["user_status"] == "False"
тру/фолс не должны быть строками

2023-12-04 11:54 UTC, Di0niz commented on src/tests/test_courses.py
>          assert new_response.json()["current_lesson"]["lesson_id"] == second_lesson.id
```suggestion
        if serializer_response := serializer_response.json():
             assert serializer_response["chapter_id"] == first_lesson.chapter_id        
             assert serializer_response["lesson_id"] == first_lesson.id
             
        if current_lesson := new_response.json()["current_lesson"]:
            assert current_lesson["chapter_id"] == second_lesson.chapter_id
            assert current_lesson["lesson_id"] == second_lesson.id
```

2023-12-04 11:54 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +            initial_lesson = {"chapter_id": None, "lesson_id": None}
всегда есть перый урок? если нет, тогда можно ничего не возвращать

2023-12-04 12:03 UTC, cosmofactory commented on src/lizaalert/courses/views.py
> +            initial_lesson = {"chapter_id": None, "lesson_id": None}
А вдруг ошибка и нет уроков.

2023-12-04 14:22 UTC, Di0niz approved these changes

2023-12-04 14:22 UTC, merged