Исправление логики current_lesson и изменение тестов
Studio-Yandex-Practicum/lizaalert_backend pull request #237
Opened 2023-11-29 14:29 UTC by cosmofactory

В текущем коде current_lesson выдается моково, чтобы фронт мог продолжить работу. 
Текущая реализация не учитывает пользователя. 
Изменена логика текущего урока следующим образом:
Текущим уроком для пользователя является:
1. Активный опубликованный урок, если его нет то
2. Следующий урок после последнего завершенного, если его нет то
3. Первый урок курса, если его нет то
4. Null

2023-12-04 09:36 UTC, Di0niz requested changes

2023-12-04 09:36 UTC, Di0niz commented on src/tests/test_courses.py
> +        url = reverse("courses-detail", kwargs={"pk": lesson.chapter.course.id})
```suggestion
        url = reverse("courses-detail", kwargs={"pk": lesson.chapter.course_id})
```

2023-12-04 09:36 UTC, Di0niz commented on src/tests/test_courses.py
> +        assert new_response.json()["current_lesson"]["chapter_id"] == second_lesson.chapter.id
```suggestion
        assert new_response.json()["current_lesson"]["chapter_id"] == second_lesson.chapter_id
```

2023-12-04 11:42 UTC, Di0niz requested changes
осталось посмотреть 404 ошибку, если курс не найден

2023-12-04 11:42 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        ).values_list("lesson", flat=True)
```suggestion
        ).values_list("lesson_id", flat=True)
```

2023-12-04 11:42 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +            course = get_object_or_404(Course, id=course_id)
если курс не найден, то 404 это ок

```suggestion
        course = get_object_or_404(Course, id= self.kwargs.get("pk", None))
```

2023-12-04 11:42 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +            if course:
по условиям, курс должен быть всегда

2023-12-04 13:40 UTC, ilin-art approved these changes

2023-12-08 09:41 UTC, cosmofactory commented on src/lizaalert/courses/views.py
> +            course = get_object_or_404(Course, id=course_id)
Такое изменение даст ошибку 404 по ручке /courses/

2023-12-08 09:42 UTC, cosmofactory commented on src/lizaalert/courses/views.py
> +            if course:
course не будет, если мы проходим по ручке /courses/

2023-12-08 12:25 UTC, Di0niz approved these changes

2023-12-08 13:07 UTC, merged