Exception handler
Studio-Yandex-Practicum/lizaalert_backend pull request #248
Opened 2023-12-08 10:01 UTC by cosmofactory

2023-12-08 12:24 UTC, Di0niz requested changes
добавь класс сериализатора для отправки ошибок

2023-12-08 12:24 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +            error = {"error": "Subscription already exists."}
нужно отправлять через serializer и по не использовать словари для отправки данных (все должно быть через схему)

2023-12-08 12:24 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +            error = {"error": "Invalid id."}
нужно отправлять через serializer и по не использовать словари для отправки данных (все должно быть через схему)

2023-12-08 21:36 UTC, ilin-art approved these changes

2023-12-08 21:36 UTC, ilin-art commented on src/lizaalert/courses/views.py
> +        except ValueError:
Если правильно понял, то get_object_or_404 должен тут вызывать исключение Http404

2023-12-08 21:36 UTC, ilin-art commented on src/lizaalert/courses/views.py
> +        except ValueError:
То же самое

2023-12-10 01:26 UTC, cosmofactory commented on src/lizaalert/courses/views.py
> +        except ValueError:
Нет, если курс не найдет объект, то он получит 404, это не вызовет except, это будет его ожидаемое поведение. 
Except здесь нужен, если в ручке courses/id/enroll, мы вместо нормального id: int передадим например id: str. 
Без try/except будет 500 ошибка.

2023-12-12 10:34 UTC, merged