Description of endpoints in swagger
Studio-Yandex-Practicum/lizaalert_backend pull request #255
Opened 2023-12-08 16:37 UTC by mr-shifty

Подписал ручки в сваггере

2023-12-09 00:14 UTC, ilin-art requested changes
Для примера посмотри ручки в сваггере в разделе /auth/, там хоршо сделаны.

2023-12-09 00:14 UTC, ilin-art commented on src/lizaalert/courses/views.py
> +    """
Думаю что не нужно писать ViewSet. Фронтенд и тестировщики могут понятия не иметь что это такое. 
И посмотри как у тебя отображается в swagger. Это описание прикрепляется к ручке /course/ , а она не делает отписку и подписку. Можешь попробовать сделать описание к get_queryset через декоратор @swagger_auto_schema(operation_description="Описание метода get_queryset")

2023-12-09 00:14 UTC, ilin-art commented on src/lizaalert/courses/views.py
> +            - kwargs: Ключевые аргументы, содержащие детали о курсе.
Параметры думаю можно не указывать, в сваггере автоматом отображаются обязательные параметры, тем более у тебя тут не информативно.

2023-12-09 00:14 UTC, ilin-art commented on src/lizaalert/courses/views.py
> +            - kwargs: Ключевые аргументы, содержащие детали о курсе.
То же самое

2023-12-09 00:14 UTC, ilin-art commented on src/lizaalert/courses/views.py
> +                404: description: Подписка на курс не найдена.
В сваггере в Responses у тебя отображается только 201. Нужно поправить через @swagger_auto_schema

2023-12-09 00:14 UTC, ilin-art commented on src/lizaalert/courses/views.py
> +        Параметры:
Лишнее

2023-12-09 00:14 UTC, ilin-art commented on src/lizaalert/courses/views.py
> +            - Response: Ответ, указывающий на успешное завершение урока (HTTP 201 Created).
В Responses свагера опять пусто, так же ничего нет про 404.

2023-12-09 00:14 UTC, ilin-art commented on src/lizaalert/courses/views.py
> +        - serializer_class: Сериализатор, преобразующий объекты уровней в формат данных, отправляемый клиенту.
Про сериализатор можно не писать

2023-12-09 00:14 UTC, ilin-art commented on src/lizaalert/courses/views.py
> +                404: Урок не найден
Про 404 в Responses свагера тоже можго добавить

2023-12-12 09:49 UTC, cosmofactory requested changes

2023-12-12 09:49 UTC, cosmofactory commented on docker-compose.yml
> +      - pgdata:/var/lib/postgresql/data/
на будущее, это изменение не касается докстрингов. Его надо пушить отдельной веткой

2023-12-12 09:49 UTC, cosmofactory commented on src/lizaalert/courses/views.py
> +        Получение QuerySet для курсов.
Распиши что входит в base_annotations and user_annotations

2023-12-15 13:27 UTC, merged