Default user level = "Новичок"
Studio-Yandex-Practicum/lizaalert_backend pull request #257
Opened 2023-12-09 03:01 UTC by ilin-art

Нужно было сделать чтобы по умолчанию у нового пользователя был уровень "Новичок". Просто поправить в модели не удалось, т.к. для присваивания любого уровня требуется подтверждение, поэтому реализовано через сигналы, когда создается новый пользователь ему присваивается подтвержденный уровень Новичок.

2023-12-12 09:55 UTC, cosmofactory approved these changes

2023-12-22 12:50 UTC, Di0niz requested changes

2023-12-22 12:50 UTC, Di0niz commented on src/lizaalert/users/models.py
>          middle = "Бывалый", "experienced"
сначало указывается ключ, потом название на русском

2023-12-22 12:50 UTC, Di0niz commented on src/lizaalert/users/models.py
> +        unique=True,
получается что количество элементов в enum и модели, будет одинаково. чем это будет отличаться от простого использования Enum.

давай добавим в модель flag с unique, по которому будет определять дефолтное значение.

2023-12-26 15:12 UTC, Di0niz requested changes

2023-12-26 15:12 UTC, Di0niz commented on src/lizaalert/users/models.py
> +@receiver(post_migrate)
давай это явно в миграции добавим, чтобы такое срабатывало не на каждую миграцию

2023-12-26 15:12 UTC, Di0niz commented on src/tests/user_fixtures/level_fixtures.py
>      [Level.objects.create(name=level["name"], description="test") for level in levels]
нужно использовать фабрики или что-то другое

2024-01-31 21:11 UTC, Di0niz requested changes

2024-01-31 21:11 UTC, Di0niz commented on src/lizaalert/users/views.py
> +            400: "Bad Request",
замени на сериализаторы как тут https://github.com/Studio-Yandex-Practicum/lizaalert_backend/pull/308

2024-01-31 21:11 UTC, Di0niz commented on src/tests/factories/users.py
> +        level, created = model_class.objects.get_or_create(name=name, defaults=kwargs)
created не используется

```suggestion
        level, _ = model_class.objects.get_or_create(name=name, defaults=kwargs)
```

2024-02-01 15:28 UTC, Di0niz requested changes

2024-02-01 15:28 UTC, Di0niz commented on src/lizaalert/users/models.py
> +            existing_record = VolunteerLevel.objects.filter(volunteer=volunteer, level=beginner_level).exists()
```suggestion
            existing_record = VolunteerLevel.objects.filter(volunteer=volunteer, level_ name=Level.LevelName.beginner).exists()
```

2024-02-04 14:20 UTC, Di0niz approved these changes
Удали sys и давай мержить

2024-02-04 14:20 UTC, Di0niz commented on src/lizaalert/users/models.py
> +import sys
Зачем нужна библиотека sys

2024-02-05 18:50 UTC, Di0niz approved these changes

2024-02-06 12:25 UTC, merged