239 remain retries
Studio-Yandex-Practicum/lizaalert_backend pull request #258
Opened 2023-12-09 11:46 UTC by vmikail

[Добавление количества попыток #239](https://github.com/Studio-Yandex-Practicum/lizaalert_backend/issues/239)
В сериализатор UserAnswerSerializer добалено поле remaining_retries, отображающее оставшееся количество попыток при прохождении квиза.

2023-12-10 16:02 UTC, ilin-art approved these changes

2023-12-10 16:02 UTC, ilin-art commented on src/lizaalert/quizzes/serializers.py
> +    def get_remaining_retries(self, instance):
Можно небольшую аннотацию написать что функция делает

2023-12-12 09:50 UTC, cosmofactory requested changes

2023-12-12 09:50 UTC, cosmofactory commented on src/lizaalert/quizzes/serializers.py
> +        return remaining_retries
```suggestion
        return max(0, max_retries - current_retries)
```

2023-12-13 09:50 UTC, cosmofactory approved these changes

2023-12-15 06:30 UTC, merged