Создание ачивок
Studio-Yandex-Practicum/lizaalert_backend pull request #264
Opened 2023-12-17 15:24 UTC by ilin-art

2023-12-18 11:57 UTC, cosmofactory approved these changes

2023-12-18 11:57 UTC, cosmofactory commented on src/lizaalert/users/admin.py
> +        if threshold_courses is not None and threshold_course is not None:
```suggestion
        if threshold_courses and threshold_course:
```

2023-12-21 08:47 UTC, cosmofactory approved these changes

2023-12-22 12:36 UTC, Di0niz requested changes

2023-12-22 12:36 UTC, Di0niz commented on src/lizaalert/users/models.py
> +    is_issued = models.BooleanField("Выдан или нет", default=True)
будем считать что выданы, давай уберем этот флаг

2023-12-22 12:36 UTC, Di0niz commented on src/lizaalert/users/models.py
>  class VolunteerBadge(models.Model):
еще нужна таблица, где будет вестись подсчет прохождений

2023-12-22 15:44 UTC, Di0niz requested changes

2023-12-22 15:44 UTC, Di0niz commented on src/tests/user_fixtures/badge_fixtures.py
> +def created_badge():
убрать, заменить на фабрики

2023-12-22 15:44 UTC, Di0niz commented on src/tests/user_fixtures/badge_fixtures.py
> +def create_volunteer_badge(create_volunteer, created_badge):
фабрика

2023-12-25 09:33 UTC, cosmofactory approved these changes

2023-12-25 14:46 UTC, Di0niz requested changes
Нужно переделать тесты, например, добавить метод, в котором будет выполняться расчет

2023-12-25 14:46 UTC, Di0niz commented on src/tests/factories/users.py
> +    name = fuzzy.FuzzyChoice(list(Level.LevelName))
чтобы не было дублей, нужно сделать поиск по полю name

2023-12-25 14:46 UTC, Di0niz commented on src/tests/test_badges.py
> +        assert volunteer_badge.id
тест на проверку работы модели лучше заменить на другое

например, добавить в код метод, который сделает заполнение VolunteerBadge и проверить работу метода

2023-12-27 09:42 UTC, ilin-art commented on src/tests/test_badges.py
> +        assert volunteer_badge.id
Я планировал добавить такой метод в следующей задаче, когда будет готова ручка окончания курса, чтобы сразу можно было протестировать работу метода.

2024-01-12 13:49 UTC, Di0niz requested changes

2024-01-12 13:49 UTC, Di0niz commented on src/lizaalert/users/admin.py
> +        fields = "__all__"
лучше явно указать перечень полей и не отображать системные

2024-01-12 13:49 UTC, Di0niz commented on src/lizaalert/users/models.py
> +    volunteer = models.OneToOneField("Volunteer", on_delete=models.CASCADE, related_name="course_completion")
лучше отделить от волонтера и в качестве типа использовать ForeignKey

2024-01-12 13:49 UTC, Di0niz commented on src/tests/test_badges.py
> +            {"volunteer": created_user.volunteer.id, "badge": created_badge.id, "created_at": "2023-01-01T12:00:00"}
```suggestion
            {
                "volunteer": created_user.volunteer.id, 
                "badge": created_badge.id, 
                "created_at": "2023-01-01T12:00:00", # тут лучше использовать datetime.now()
             }
```

2024-01-12 13:49 UTC, Di0niz commented on src/tests/test_badges.py
> +            "created_at": "2023-01-01T12:00:00",
лучше использовать datetime.now()

это поле должно автозаполняемым, если не заполнено, то заполняется текущей датой

2024-01-12 13:49 UTC, Di0niz commented on src/tests/test_badges.py
> +        assert "Этот значок уже был выдан данному волонтеру." in form.errors["__all__"]
здесь ошибка должна быть привязана к волонтеру

2024-01-12 13:49 UTC, Di0niz commented on src/tests/test_badges.py
> +    def test_volunteer_courses_completion(self):
что нужно проверить? заполнение БД проверять не надо

2024-01-12 13:49 UTC, Di0niz commented on src/tests/test_badges.py
> +        VolunteerBadge.objects.create(volunteer=created_user.volunteer, badge=created_badge)
для этого лучше создать фабрику и сразу ее использовать

2024-01-19 11:58 UTC, Di0niz approved these changes

2024-01-19 15:11 UTC, merged