Добавление полей и механик работы Подписок
Studio-Yandex-Practicum/lizaalert_backend pull request #267
Opened 2023-12-20 17:16 UTC by cosmofactory

**models.py**
- Добавляем новые статусы
- при создании подписки определяем статус в зависисмости от даты начала курса
- при запросе на обновление статуса проверяем текущий статус и обновляем подписку в БД, только в случае если курс не закончен

**permissions.py**
- новый permission для доступа к урокам в зависимости от статуса подписки на курс

**utils.py**
- в сериализаторе возвращаем статус подписки для пользователя
- функции обновления статусов одной подписки или всех подписок (на данный момент вызываются в queryset или permission)

**views.py**
- обновляем подписки при обновлении страницы, для одного курса или всех
- добавляем поле user_status в сериализатор при enroll

**тесты**
- добавляем моковый permission, чтобы не создавать подписки, когда этого не требуется
- обновляем тесты/добавляем новые

2023-12-21 19:19 UTC, ilin-art approved these changes

2023-12-21 19:19 UTC, ilin-art commented on src/lizaalert/courses/permissions.py
> +                return False
Здесь по идее можно немного оптимизировать запрос
```suggestion
if user.subscriptions.filter(course=course, status__in=access_statuses).exists():
        return True
```

2023-12-21 19:19 UTC, ilin-art commented on src/lizaalert/courses/utils.py
> +    except Exception:
Почему бы не использовать более ожидаемое исключение
```suggestion
    except Subscription.DoesNotExist```

2023-12-22 10:10 UTC, cosmofactory commented on src/lizaalert/courses/permissions.py
> +                return False
Топчик, можно даже еще лаконичнее:
```suggestion
        if user.is_authenticated:
            try:
                return user.subscriptions.filter(course=course, status__in=access_statuses).exists()
```

2023-12-22 12:31 UTC, Di0niz requested changes

2023-12-22 12:31 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        ACTIVE = 1, "Начата"
это уже не TextChoices, а IntChoices

2023-12-22 12:31 UTC, Di0niz commented on src/lizaalert/courses/models.py
>          NOTSTARTED = 0, "Не начат"
список дублируется в нескольких местах, давай его вынесем из классов и объявим в одном месте

2023-12-22 12:31 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +    course = models.ForeignKey(Course, on_delete=models.PROTECT, related_name="subscription")
related_name  во множественном числе нужно использовать, но здесь лучше не получать список подписок для курса (для этого лучше явно запрос написать)

```suggestion
    course = models.ForeignKey(Course, on_delete=models.PROTECT, related_name="+")
```

2023-12-22 12:31 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +            if timezone.now().date() < self.course.start_date:
статус должен расчитываться в сериализаторе и не перезаписываться от времени

2023-12-22 12:31 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        course_progress_status = CourseProgressStatus.objects.filter(course=self.course, user=self.user).first()
вложенных запросов лучше избегать

давай при завершении курса какой нить флажок поднимем, что подписка завершена

2023-12-22 12:31 UTC, Di0niz commented on src/lizaalert/courses/permissions.py
> +        update_one_subscription(user, course)
при проверке прав доступа не должно быть обновлений бд

2023-12-22 12:31 UTC, Di0niz commented on src/lizaalert/courses/utils.py
> +def update_subscriptions(user):
не будем обновлять, давай подумаем над другой механикой

2023-12-26 09:42 UTC, Di0niz requested changes

2023-12-26 09:42 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +        NOTSTARTED = 0, "Не начат"
```suggestion
        NOT_STARTED = 0, "Не начат"
```

2023-12-26 09:42 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +def update_or_create_progress_status(model, user, instance, field, status, lookup_field):
сделай через миксин и добавь к моделям, возможно где-то переопределишь

2023-12-26 09:42 UTC, Di0niz commented on src/lizaalert/courses/utils.py
> +def check_course_available(course):
сделай частью класса курс  (как property)

`available` или `is_available`

2023-12-26 09:42 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +            serializer = ErrorSerializer({"detail": "Invalid id."})
какой id инвлид? лучше сделать через drf exceptions

2023-12-26 09:42 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +        subscription, created = Subscription.objects.get_or_create(user=user, course=course)
запись на курс выдели в отдельный мето

2023-12-26 09:42 UTC, Di0niz commented on src/tests/test_courses.py
> +            print(subscription_response)
здесь print не нужен

2023-12-26 09:42 UTC, Di0niz commented on src/tests/user_fixtures/course_fixtures.py
> +def mock_enrollment_permission():
здесь пачт проверок не нужен, они должны корректно отрабатывать

2024-01-12 13:56 UTC, Di0niz requested changes

2024-01-12 13:56 UTC, Di0niz commented on src/lizaalert/courses/exceptions.py
> +class BadRequestException(APIException):
лучше наследоваться от классов с этими кодами ошибок и переопределить только важное

2024-01-12 13:56 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +def status_update_mixin():
нужно добавить проверку, по закрытию родителя

2024-01-12 13:56 UTC, Di0niz commented on src/lizaalert/courses/models.py
>          lesson_qs = Lesson.objects.filter(chapter=self.chapter, status=self.LessonStatus.PUBLISHED).aggregate(
этот код в миксин перенести

2024-01-15 19:31 UTC, Di0niz commented
MIL-4

2024-01-15 19:38 UTC, Di0niz requested changes

2024-01-15 19:38 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +            model_name = f"{self.__class__.__name__}ProgressStatus"
так вычислять не надо, передавай в миксине класс статусов

2024-01-15 19:38 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                    user=user, progress=BaseProgress.ProgressStatus.FINISHED, **filter_kwargs
будет ли работать self.ProgressStatus.Finished?

2024-01-15 19:38 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                    getattr(parent_attr, "finish")(user)
уже parent известен, можно сделать `parent.finish(user)`

2024-01-15 19:38 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                filter_string = f"{self.__class__.__name__.lower()}__{parent}"
self.__class__ - часто используется, выделил переменную

2024-01-15 19:38 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +                filter_string = f"{self.__class__.__name__.lower()}__{parent}"
попробуй изменить запросы так, чтобы фильтровать по id

2024-01-15 19:45 UTC, Di0niz approved these changes

2024-01-15 20:00 UTC, merged