Cohort models admin
Studio-Yandex-Practicum/lizaalert_backend pull request #269
Opened 2023-12-22 16:19 UTC by mr-shifty

Сделал модели когорт

2023-12-25 10:06 UTC, cosmofactory requested changes

2023-12-25 10:06 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="cohorts", verbose_name="Курс")
Не надо удалять когорты, если удалили курсы, эта информация еще может пригодиться

2023-12-25 10:06 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +    cohort_number = models.PositiveIntegerField(verbose_name="Номер группы", unique=True)
В таске это поле должно рассчитываться автоматически

2023-12-25 10:06 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +    - cohort_number: уникальный номер группы в рамках курса
Не хватает:
 - дата начала
 - дата окончания
 - количество студентов
 - преподаватель

2023-12-25 14:39 UTC, Di0niz requested changes

2023-12-25 14:39 UTC, Di0niz commented on src/.python-version
> +3.10
нужно удалить лишние файлы

2023-12-25 14:39 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> -
лучше не делать дополнительных изменений, чтобы не увеличивать PR

2023-12-25 14:39 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +    cohort_number = models.PositiveIntegerField(verbose_name="Номер группы", unique=True)
поле не уникально, уникально только в пределах курса

2023-12-25 14:39 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        ordering = ("cohort_number",)
в пределах курса

2024-01-16 18:49 UTC, cosmofactory requested changes

2024-01-16 18:49 UTC, cosmofactory commented on src/lizaalert/courses/migrations/0019_Update_cohort_number_in_cohort.py
> +    ]
Миграции надо объединить в один файл

2024-01-16 18:49 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +    cohort_number = models.PositiveIntegerField(verbose_name="Номер группы", unique=False)
Надо добавить уникальность номера когорты у конкретного курса

2024-01-16 18:49 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +    teacher = models.CharField(max_length=255, verbose_name="Преподаватель", null=True, blank=True)
У нас будет CharField или FK на User?

2024-01-16 18:49 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +        Cohort, on_delete=models.PROTECT, related_name="cohort", null=True, blank=True, verbose_name="Группа"
related_name здесь наверное будет все же subscriptions

2024-01-16 18:49 UTC, cosmofactory commented on src/lizaalert/courses/models.py
>          constraints = [
У нас должна быть только одна подписка на курс с какой то когортой. Нужно добавить уникальность когорта-курс.

2024-01-17 14:14 UTC, cosmofactory requested changes

2024-01-17 14:14 UTC, cosmofactory commented on src/lizaalert/courses/admin.py
> +
Добавь еще ordering

2024-01-17 14:14 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +    cohort_number = models.PositiveIntegerField(verbose_name="Номер группы", unique=True)
Опять же, номер когорты не уникален, здесь не нужен unique=True, здесь нужен UniqueConstraint = [course, cohort_number]

@Di0niz это поле заполняется пользователем или рассчитывается автоматически?

2024-01-17 14:14 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +    cohort = models.ForeignKey(
Здесь нужен unique constraint [cohort, course]

2024-01-17 14:50 UTC, mr-shifty commented on src/lizaalert/courses/admin.py
> +
По какому полю лучше? По номеру когорты?

2024-01-19 12:48 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +    cohort_number = models.PositiveIntegerField(verbose_name="Номер группы", unique=True)
UniqueConstraint = [course, cohort_number]

Да, номер должен рассчитываться как последний номер по курсу + 1

2024-01-19 16:43 UTC, mr-shifty commented on src/lizaalert/courses/models.py
> +    cohort = models.ForeignKey(
@cosmofactory Он не видит поле когорту почему-то. Все остальное пофиксил

2024-01-22 16:44 UTC, cosmofactory requested changes

2024-01-22 16:44 UTC, cosmofactory commented on src/.python-version
> +3.10
Этих файлов здесь не должно быть

2024-01-22 16:44 UTC, cosmofactory commented on src/lizaalert/courses/migrations/0020_Update_consraint_subscription.py
> +    ]
Файлы миграций надо объединить

2024-01-22 16:44 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> -                fields=["user", "course"],
Не нужно удалять этот констрейн, он тоже нужен. 
Джанго позволяет делает более одного констрейна.

2024-01-22 16:44 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +    cohort_number = models.PositiveIntegerField(verbose_name="Номер группы")
Это поле должно рассчитываться автоматически при создании модели.  
Логика примерно следующая:
    1. Создается новая когорта
    2. В процессе ее создания узнается последний номер когорты для того курса, к которому привязана эта когорта
    3. Новая_когда.cohort_number = Последняя_когорта_для_курса.cohort_number + 1
  
  Чтобы это сделать, тебе надо переопределить метод save() в модели. 
Должно получиться что то похожее на это, но с учетом наших особенностей:

https://stackoverflow.com/a/33938376

2024-01-23 15:03 UTC, cosmofactory requested changes
В целом хорошо, почти все готово, пусть еще Денис посмотрит

2024-01-23 15:03 UTC, cosmofactory commented on src/.python-version
> +3.10
Файл по прежнему здесь

2024-01-23 15:03 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +            last_cohort = Cohort.objects.filter(course=self.course).order_by("-cohort_number").first()
```suggestion
            last_cohort = Cohort.objects.filter(course=self.course).aggregate(max_number=Max('cohort_number'))['max_number']
```
Нам не нужен весь объект последней когорты, нам необходим только самый большой порядковый номер, его проще высчитать и получить на стороне БД.

2024-01-23 17:39 UTC, cosmofactory requested changes

2024-01-23 17:39 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +    cohort_number = models.PositiveIntegerField(verbose_name="Номер группы")
```suggestion
    cohort_number = models.PositiveIntegerField(verbose_name="Номер группы", help_text="Данное поле будет рассчитано автоматически при сохранении.")
```

2024-01-23 17:39 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +    cohort_number = models.PositiveIntegerField(verbose_name="Номер группы", editable=False)
Сделав его editable=False, мы потеряем возможность видеть его в админке сайта. 
Лучше сделать его в настройках админки read_only, либо добавить help_text, что оно рассчитывается автоматически.

2024-01-23 17:39 UTC, cosmofactory commented on src/lizaalert/courses/admin.py
> +class CohortInline(admin.TabularInline):
Inline админка используется тогда, когда ты вставляешь админку модели в админку другой модели (Как у нас например сделано с курсом - Админка Курса содержит inline админку Главы)
Здесь же мы никуда не вставляем эту админку, так что можно делать не inline.

2024-01-23 17:39 UTC, cosmofactory commented on src/lizaalert/courses/admin.py
> +    ordering = ("cohort_number_display",)
Везде где написано "cohort_number_display", так работать не будет, здесь передаются поля, а не методы.

2024-01-23 17:39 UTC, cosmofactory commented on src/lizaalert/courses/admin.py
> +admin.site.register(Cohort)
Эту строчку можно удалить и давай сделаем такую админку:

```
@admin.register(Cohort)
class CohortAdmin(admin.ModelAdmin):
    """
    Админка когорты.

    При созданиии объекта исключается поле cohort_number.
    """

    model = Cohort
    extra = 1
    list_display = (
        "cohort_number",
        "course",
        "start_date",
        "end_date",
        "teacher",
        "created_at",
        "updated_at",
    )
    ordering = ("-updated_at",)

    def get_fields(self, request, obj=None):
        fields = super().get_fields(request, obj)
        if not obj:
            fields.remove('cohort_number')
        return fields
```

2024-01-23 17:39 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +    cohort_number = models.PositiveIntegerField(verbose_name="Номер группы", editable=False)
Сделал вариант админки, как сделать лучше

2024-01-23 18:25 UTC, cosmofactory approved these changes

2024-01-24 12:43 UTC, Di0niz requested changes

2024-01-24 12:43 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        return fields
не надо хардкодить удаление поля

2024-01-24 12:43 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        "cohort_number",
можно не отображать здесь
```suggestion
```

2024-01-24 12:43 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        with transaction.atomic():
не надо создавать вложенных транзакций

2024-01-24 12:43 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        return f"{self.course.title} - Группа {self.cohort_number}"
```suggestion
        return f"{self.course_id} - Группа {self.cohort_number}"
```

не нужно делать циклических запросов

2024-01-24 12:43 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +            max_cohort_number = Cohort.objects.filter(course=self.course).aggregate(Max("cohort_number"))[
укажи список полей, которые получаешь в запросе

2024-01-24 12:43 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        return f"{self.course.title} - Группа {self.cohort_number}"
Cohord обозначает группу, писать словами группа не надо

2024-01-24 12:43 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +    def get_fields(self, request, obj=None):
добавь поле, в котором будет отображаться человекочитаемое название
для это переопредели queryset чтобы подтягивал название курса

2024-01-26 07:28 UTC, Di0niz requested changes

2024-01-26 07:28 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> -
отступы удалять не надо, нужно минимизировать количество касаний

2024-01-27 17:47 UTC, mr-shifty commented on src/lizaalert/courses/models.py
> +            max_cohort_number = Cohort.objects.filter(course=self.course).aggregate(Max("cohort_number"))[
Не очень понял. Тут всего одно поле, которое вычисляет номер когорты в этом методе

2024-01-29 20:02 UTC, Di0niz requested changes

2024-01-29 20:02 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        return obj.course_title
здесь не нужна аннотация


```suggestion
    def get_queryset(self, request):
        qs = super().get_queryset(request).select_related("course")
        return qs

    def course_title(self, obj):
        return obj.course.title
```

2024-01-29 20:02 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        return fields
что именно здесь переопределяется?

```suggestion
```

2024-01-29 20:02 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> -
добавь отступ

2024-01-29 20:02 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> -
добавь отступ

2024-01-30 13:16 UTC, cosmofactory commented on src/lizaalert/courses/admin.py
> +        return obj.course_title
Давайте сделаем так: 
https://docs.djangoproject.com/en/5.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_select_related

с @Di0niz согласовано

2024-02-02 11:25 UTC, cosmofactory approved these changes

2024-02-02 11:25 UTC, cosmofactory commented on src/lizaalert/courses/admin.py
> +    def get_queryset(self, request):
Эта функция не нужна, мы подтянули select_related в 85й строке.

2024-02-02 11:25 UTC, cosmofactory commented on src/lizaalert/courses/migrations/0019_Created_model_cohort.py
> +# Generated by Django 3.2.20 on 2024-01-23 10:05
сейчас последняя миграция 20ая, нужно подтянуть ветку dev, сделать новые миграции и пушнуть их сюда

2024-02-03 08:57 UTC, mr-shifty commented on src/lizaalert/courses/migrations/0019_Created_model_cohort.py
> +# Generated by Django 3.2.20 on 2024-01-23 10:05
![Снимок экрана от 2024-02-03 11-56-21](https://github.com/Studio-Yandex-Practicum/lizaalert_backend/assets/118600823/3d82d425-c563-43d8-8a15-537b246d27f4)
Я же подтянул и сделал

2024-02-03 18:37 UTC, cosmofactory approved these changes

2024-02-04 11:43 UTC, merged