261 profile badges list
Studio-Yandex-Practicum/lizaalert_backend pull request #270
Opened 2023-12-25 07:14 UTC by vmikail

[ Ручка ачивок пользователя #261 ](https://github.com/Studio-Yandex-Practicum/lizaalert_backend/issues/261)

2023-12-25 09:52 UTC, cosmofactory commented on src/lizaalert/users/views.py
> +class VolunteerBadgeList(views.APIView):
Не хватает аннотации класса.

2023-12-25 09:52 UTC, cosmofactory commented on src/lizaalert/users/views.py
> +    def get(self, request):
А почему APIView? Здесь вроде не сильно кастомная операция, ViewSet прекрасно с ней справится и будет проще для расширения

2023-12-25 09:52 UTC, cosmofactory commented on src/lizaalert/users/views.py
> +        queryset = Volunteer.objects.filter(pk=volunteer.pk)
```suggestion
        queryset = Volunteer.objects.filter(user=request.user)
```

2023-12-25 14:35 UTC, Di0niz requested changes

2023-12-25 14:35 UTC, Di0niz commented on src/lizaalert/users/views.py
> +        return Response(status=status.HTTP_204_NO_CONTENT)
так как ожидается список то, нужно вернуть список

2023-12-25 14:35 UTC, Di0niz commented on src/tests/test_volunteer_profile.py
> +        assert response.status_code == status.HTTP_200_OK
почему вернули бейджи, если здесь нет их создания?

Если они создаются где-то в другом месте, то создай пользователя и присвой бейджи (явное лучше не явного)

2024-01-12 14:01 UTC, Di0niz requested changes

2024-01-12 14:01 UTC, Di0niz commented on src/tests/factories/users.py
> +    @classmethod
зачем нужно переопределять _create?

2024-01-12 14:01 UTC, Di0niz commented on src/tests/test_volunteer_profile.py
> +        VolunteerBadge.objects.create(volunteer=created_user.volunteer, badge=created_badge)
нужно добавить фабрику для VolunterBadge

2024-01-12 14:01 UTC, Di0niz commented on src/lizaalert/users/serializers.py
> +        model = Volunteer
BadgesList должна на вход получать список бейдежев (нужно изменить запрос во view функции)

2024-01-12 14:01 UTC, Di0niz commented on src/tests/test_volunteer_profile.py
> +        assert response.status_code == status.HTTP_200_OK
нужно проверить, что вернулись данные в соответствии ожиданиями

2024-01-19 09:08 UTC, Di0niz requested changes

2024-01-19 09:08 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +class Chapter(TimeStampedModel, order_number_mixin(CHAPTER_STEP, "course"), status_update_mixin(parent="course")):
лучше добавить магическую запятую в список, чтобы каждый класс был на отдельной 

```suggestion
class Chapter(
    TimeStampedModel,
    order_number_mixin(CHAPTER_STEP, "course"),
    status_update_mixin(parent="course"),
):
```

2024-01-19 09:08 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +class LessonProgressStatus(TimeStampedModel, BaseProgress):
```suggestion
class LessonProgressStatus(TimeStampedModel, BaseProgress,):
```

2024-01-19 09:08 UTC, Di0niz commented on src/lizaalert/courses/models.py
>          return f"Chapter {self.chapter.title}: {self.user.username}"
убрать получение данных из других таблиц

2024-01-19 09:08 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +class CourseProgressStatus(TimeStampedModel, BaseProgress):
```suggestion
class CourseProgressStatus(TimeStampedModel, BaseProgress,):
```

2024-01-19 09:08 UTC, Di0niz commented on src/lizaalert/courses/permissions.py
> +                return user.subscriptions.filter(course=course).exists() and course.is_available
почему тут будет exception?

```suggestion
                return Subscription.objects.filter(user=<>, course=course, course__is_available=True).exists()
```

2024-01-19 09:08 UTC, Di0niz commented on src/lizaalert/courses/serializers.py
> +            if obj.user_status == Subscription.Status.ENROLLED and obj.is_available:
выглядит так, что нужно разделять вычисляемые статусы и статусы подписки

нужно в модель подписки добавить вычисляемое поле status  и там описать такую магию

2024-01-19 09:08 UTC, Di0niz commented on src/lizaalert/users/migrations/0006_auto_20231223_1851.py
если эта миграция на проде, то удалять будет больно, перед выкаткой нужно откатывать эту миграцию на сервере

2024-01-19 16:00 UTC, Di0niz requested changes

2024-01-19 16:00 UTC, Di0niz commented on src/lizaalert/users/serializers.py
> +            "threshold_course",
```suggestion
            "issued_for",
```

2024-01-19 16:00 UTC, Di0niz commented on src/lizaalert/users/views.py
> +        serializer = BadgesListSerializer(queryset, context={"request": request}, many=True)
```suggestion
        queryset = Badge.objects.filter(id__in=VolontuerBadge.objects.filter(user=user).values('badge_id'))
        serializer = BadgeSerializer(queryset, many=True)
```

2024-01-19 16:00 UTC, Di0niz commented on src/lizaalert/users/views.py
> +        return Response(list())
```suggestion
        return Response(serializer.data)
```

2024-01-22 16:56 UTC, cosmofactory commented
@vmikail Я вижу, что у тебя много борьбы с isort и black. 
Это продвинутые библиотеки и они могут сделать очень многое за тебя, посмотри их документацию. 
Если коротко, то находясь в директории /src/, например, ты можешь ввести в терминале "isort .", а затем "black ." и твой код будет отформатирован в соответствии с правилами.

2024-01-26 07:25 UTC, Di0niz requested changes

2024-01-26 07:25 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> -
верни отступы, нужно делать минимум касаний по коду

2024-01-26 07:25 UTC, Di0niz commented on src/tests/test_volunteer_profile.py
> -
верни строку

2024-01-26 07:25 UTC, Di0niz commented on src/tests/test_volunteer_profile.py
> +        response = user_client.get(self.url).json()
проверь статус ответа 200

2024-01-26 07:51 UTC, vmikail commented on src/lizaalert/courses/admin.py
> -
локальный black съел отступы и строки. :(

2024-01-26 10:45 UTC, Di0niz requested changes

2024-01-26 10:45 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +
тут не нужна пустая строка, старый код по возможности не меняй

2024-01-26 10:59 UTC, cosmofactory commented on src/lizaalert/users/urls.py
> +    path("profile/badges/", VolunteerBadgeListViewSet.as_view({"get": "list"}), name="badgeslist"),
Если это у тебя ViewSet, зачем его регистрировать as_view?

https://www.django-rest-framework.org/api-guide/viewsets/

лучше отдать это все роутеру

2024-01-26 13:39 UTC, Di0niz approved these changes

2024-01-26 14:58 UTC, cosmofactory approved these changes

2024-01-26 15:00 UTC, merged