MIL-8 Добавить ручку current_lesson и тест
Studio-Yandex-Practicum/lizaalert_backend pull request #274
Opened 2024-01-16 10:54 UTC by cosmofactory

2024-01-16 18:39 UTC, ilin-art approved these changes

2024-01-19 09:16 UTC, Di0niz requested changes

2024-01-19 09:16 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +    def _get_current_lesson(self, **kwargs):
давай эту магию пересем в сериализатор

этот код должен быть там: в сериализатор пробрасываешь источник, а далее он по правилам собирает данные

2024-01-19 11:56 UTC, Di0niz approved these changes

2024-01-19 12:00 UTC, merged