MIL-7 Добавить ручку завершения курса, добавить тест
Studio-Yandex-Practicum/lizaalert_backend pull request #276
Opened 2024-01-16 13:02 UTC by cosmofactory

2024-01-16 18:01 UTC, ilin-art approved these changes

2024-01-19 09:14 UTC, Di0niz requested changes

2024-01-19 09:14 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +        course_completion_event(course, user)
```suggestion
        after_course_completion_event(course, user)
```

давай это сделаем на сигналах

2024-01-19 09:14 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +        course_completion_event(course, user)
https://docs.djangoproject.com/en/5.0/topics/signals/

2024-01-19 13:46 UTC, Di0niz approved these changes

2024-01-19 14:19 UTC, merged