TM-15 Присвоение ачивок после завершения курса
Studio-Yandex-Practicum/lizaalert_backend pull request #302
Opened 2024-01-25 16:25 UTC by ilin-art

После вызова эндпоинта завершения курса `/api/v1/courses/{course.id}/complete/` инкрементируется число пройденных курсов пользователя и далее происходит проверка на наличие ачивок которые можно присвоить пользователю, если такие находятся, то происходит присвоение этих ачивок.

2024-01-26 07:32 UTC, Di0niz requested changes

2024-01-26 07:32 UTC, Di0niz commented on src/lizaalert/courses/signals.py
> +    course = kwargs.get("course")
если значения нет, то нужно кидать ошибку

2024-01-26 07:32 UTC, Di0niz commented on src/lizaalert/users/utils.py
> +    volunteer_completion, created = VolunteerCourseCompletion.objects.get_or_create(volunteer=volunteer)
можно сразу создать нужно запись и если она создана, то второй раз не записывать

2024-01-26 07:32 UTC, Di0niz commented on src/lizaalert/users/utils.py
> +def assign_achievements(user, course_id):
разбей на два метода, расчет для механики с ачивками за курс и механики с посчетом

2024-01-26 07:32 UTC, Di0niz commented on src/lizaalert/users/utils.py
> +            VolunteerBadge.objects.create(volunteer=user.volunteer, badge=badge, course_id=course_id)
нужно без запросов с цикле, посмотри на batch запросы

2024-01-26 15:57 UTC, Di0niz requested changes

2024-01-26 15:57 UTC, Di0niz commented on src/tests/test_badges.py
> +        volunteer = Volunteer.objects.get(user=user)
нужно создавать объект через фабрику

2024-01-29 12:58 UTC, ilin-art commented on src/tests/test_badges.py
> +        volunteer = Volunteer.objects.get(user=user)
Волонтер у нас создается автоматом при создании юзера, я только достал волонтера, а юзер из фабрики создается.

2024-01-29 19:58 UTC, Di0niz requested changes

2024-01-29 19:58 UTC, Di0niz commented on src/lizaalert/users/utils.py
> +    completed_courses_count = VolunteerCourseCompletion.objects.get(volunteer__user=user).completed_courses_count
если студент еще не прошел курс, то где вернет None и будет ошибка

2024-01-29 19:58 UTC, Di0niz commented on src/tests/test_badges.py
> +        _ = VolunteerCourseCompletion.objects.create(volunteer=volunteer)
а если еще ничего не прошел? сделай проверку начиная с 0

можно в цикле перебрать курсы и проверить, что счетчик точно инкрементит

2024-01-29 19:58 UTC, Di0niz commented on src/tests/test_badges.py
> +        _ = VolunteerCourseCompletion.objects.create(volunteer=volunteer)
сделай тесты без заглушек, все дополнительные связи должны быть созданы внутри

2024-01-29 19:58 UTC, Di0niz commented on src/tests/test_badges.py
> +        volunteer = Volunteer.objects.get(user=user)
может быть он как-то может вычислиться из таблицы user

2024-02-01 17:46 UTC, ilin-art commented on src/tests/test_badges.py
> +        _ = VolunteerCourseCompletion.objects.create(volunteer=volunteer)
Если еще ничего не прошел то такого объекта и нет, он создается только после прохождения курса, сразу со значением 1.

Он ведь не по курсам инкрементит, а после вызова функции, иначе если у курса изменится статус или его удалят счетчик в обратную сторону может пойти. Могу через range() сделать вызов функции и проверку.

2024-02-02 11:27 UTC, cosmofactory approved these changes

2024-02-04 14:18 UTC, Di0niz approved these changes

2024-02-04 16:23 UTC, merged