TM-33 Починить swagger для ручки profile
Studio-Yandex-Practicum/lizaalert_backend pull request #308
Opened 2024-01-26 17:44 UTC by vmikail

Добавлен swagger к ручке профиля.

2024-01-26 20:25 UTC, Di0niz requested changes

2024-01-26 20:25 UTC, Di0niz commented on src/lizaalert/users/views.py
> +        responses={200: VolunteerSerializer()},
нужно добавить описание статусов
204 
404

2024-01-26 20:25 UTC, Di0niz commented on src/lizaalert/users/views.py
> +        responses={200: VolunteerSerializer()},
добавить описание возможных статусов
404
400

2024-01-27 18:36 UTC, vmikail commented on src/lizaalert/users/views.py
> +        responses={200: VolunteerSerializer()},
Подскажи, пожалуйста, а 204 возможен? Эта ручка только для того чтобы пользователь мог посмотреть свой профиль, по крайней мере пока. А если пользователь является волонтером, то он в любом случае получает данные.
Как я понимаю в этом сценарии возможны только 401 и 404, помимо 200.
Первый в том случае если ручку использует не авторизованный пользователь.
Второй в том случае если пользователь не является волонтером.
Или я не так понял? ))

2024-01-29 19:54 UTC, Di0niz requested changes

2024-01-29 19:54 UTC, Di0niz commented on src/lizaalert/users/views.py
> +        responses={200: VolunteerSerializer(), 204: "No Content", 404: "Not Found"},
проверь и замени на актуальные значения

204 - возвращает ""
404 - json ?

```suggestion
        responses={200: VolunteerSerializer(), 204: {}, 404: "Not Found"},
```

2024-01-29 19:54 UTC, Di0niz commented on src/lizaalert/users/views.py
> +        responses={200: VolunteerSerializer(), 400: "Bad Request", 404: "Not Found"},
проверь и замени на актуальные значения

200 -  json ?
404 - json ?

2024-01-31 21:09 UTC, Di0niz approved these changes

2024-02-01 06:30 UTC, merged