MIL-46 Связь прогресса с подпиской
Studio-Yandex-Practicum/lizaalert_backend pull request #309
Opened 2024-01-26 19:20 UTC by cosmofactory

Технический PR, пока не готово.

2024-01-27 21:54 UTC, ilin-art approved these changes

2024-01-27 21:54 UTC, ilin-art commented on src/tests/test_courses.py
> +        pprint(response_course.json())
отладочный?

2024-01-29 19:52 UTC, Di0niz requested changes

2024-01-29 19:52 UTC, Di0niz commented on src/lizaalert/courses/migrations/0019_auto_20240126_1429.py
> +class Migration(migrations.Migration):
добавь замену текущих пользователей на использование подписок

2024-01-29 19:52 UTC, Di0niz commented on src/lizaalert/courses/mixins.py
> +        def finish(self, user, subscription):
точно ли нужно использовать `user`

2024-01-29 19:52 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +    def activate(self, user, subscription):
`user` не используется

2024-01-29 19:52 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        "subscription",
сделай в админке (в форме списка) красивое отображение подписки

2024-01-30 16:58 UTC, Di0niz requested changes

2024-01-30 16:58 UTC, Di0niz commented on src/lizaalert/courses/migrations/0019_auto_20240126_1429.py
> +            STORAGE[model.__name__][obj.id] = obj.user.id
```suggestion
        STORAGE[model.__name__] = {obj.id: obj.user_id for obj in model.objects.all()}
```

2024-01-30 16:58 UTC, Di0niz commented on src/lizaalert/courses/migrations/0019_auto_20240126_1429.py
> +        return lesson_progress.lesson.chapter.course
в queryset добавить поддержку связанных таблиц

2024-01-30 16:58 UTC, Di0niz commented on src/lizaalert/courses/migrations/0019_auto_20240126_1429.py
> +    operations = [
нужно изменить порядок операций:

- сначала добавляешь новое поле
- заполняешь его из поля user
- удаляешь старое поле

можно разделить и сделать это в разные миграциях (посмотри по доке создать пустую миграцию)

2024-01-31 13:36 UTC, Di0niz requested changes

2024-01-31 13:36 UTC, Di0niz commented on src/lizaalert/courses/migrations/0019_auto_20240126_1429.py
> +                sys.stderr.write(str(e) + "\n")
```suggestion
    progresses = [
        (apps.get_model('courses', 'CourseProgressStatus'), 'course', lambda obj: obj.course),
        (apps.get_model('courses', 'LessonProgressStatus'), 'lesson__chapter__course', lambda obj: obj.lesson.chapter.course),
        (apps.get_model('courses', 'ChapterProgressStatus'), 'chapter__course', lambda obj: obj.chapter.course),
    ]

    for model, sel_related, get_course_func in progresses:
        queryset = model.objects.select_related(sel_related).all()
       for obj in queryset:
            course = get_course_func(obj)
            try:
                subscription = Subscription.objects.get(user_id=obj.user_id, course=course)
            except Subscription.DoesNotExist as e:
                subscription = Subscription.objects.create(user_id=obj.user_id, course=course)

            obj.subscription_id = subscription.id
            obj.save(update_fields=['subscription_id'])
```

2024-01-31 13:38 UTC, Di0niz approved these changes

2024-01-31 13:52 UTC, merged