Исправление бага MIL-37 /comlete
Studio-Yandex-Practicum/lizaalert_backend pull request #316
Opened 2024-01-30 20:25 UTC by Leontiev93

Дополнение теста, который проверяет что пройдены все главы, соответственно и урок, только после этого можно завершать курс.

2024-01-30 21:26 UTC, cosmofactory requested changes

2024-01-30 21:26 UTC, cosmofactory commented on src/lizaalert/courses/views.py
> +        user_completed_chapters = user.user_chapter_status.all().filter(progress=2, chapter__course=kwargs["pk"])
Это затратная по ресурсам операция, ее надо делать на стороне БД

2024-01-30 21:26 UTC, cosmofactory commented on src/lizaalert/courses/views.py
> +        total_completed_chapters = course.chapters.all()
1. Здесь наверное не total_completed_chapters, а total_chapters
2. Получить общее число глав курса нам также надо на сторое БД, нам нужно знать только количество глав, нам не надо подтягивать все объекты глав.

2024-01-30 21:26 UTC, cosmofactory commented on src/lizaalert/courses/views.py
> +        if len(user_completed_chapters) == len(total_completed_chapters):
Курс завершает встроенный метод в модель Course под названием finish()
Соответственно если мы захотим завершать курс еще где то, мы будем тоже вызывать метод finish, и для этого нам придется копировать код отсюда.  Так лучше не делать, это нарушает принцип Don't Repeat Yourself, проверку но то, завершены ли главы Курса надо делать внутри метода .finish()

2024-01-30 21:26 UTC, cosmofactory commented on src/tests/test_courses.py
> +            assert response.status_code == status.HTTP_403_FORBIDDEN
Нам не важна внутрення логика, нам надо проверить только 2 вещи:
1. Курс не завершается если не все уроки пройдены
2. Курс завершается если все уроки пройдены
```suggestion
        url = reverse("courses-complete", kwargs={"pk": course.id})
        url_course = reverse("courses-detail", kwargs={"pk": course.id})
        response = user_client.post(url)
        assert response.status_code == status.HTTP_403_FORBIDDEN

        lessons = Lesson.objects.filter(chapter_course=course)
        for lesson in lessons:
            lesson.finish(user)
        
        response = user_client.post(url)
        response_course = user_client.get(url_course)
        assert response.status_code == status.HTTP_200_OK
        assert response_course.json()["user_status"] == Subscription.Status.COMPLETED
```

2024-01-30 21:26 UTC, cosmofactory commented on src/tests/test_courses.py
> +        if len(user_completed_chapters) == len(total_completed_chapters):
Эта строка никогда не вернет True. Мы создаем Курс с непройденными уроками, никто их не проходил, соответственно мы никогда не проверим, что позвращается верный ответ при корректном завершении курса.

2024-01-31 06:26 UTC, Leontiev93 commented on src/lizaalert/courses/views.py
> +        user_completed_chapters = user.user_chapter_status.all().filter(progress=2, chapter__course=kwargs["pk"])
Не тянуть all()? просто сразу filter ?

2024-01-31 06:28 UTC, Leontiev93 commented on src/lizaalert/courses/views.py
> +        total_completed_chapters = course.chapters.all()
1. Согласен. 
2. Использовать course.chapters.all().count() ?

2024-01-31 06:33 UTC, Leontiev93 commented on src/tests/test_courses.py
> +            assert response.status_code == status.HTTP_403_FORBIDDEN
Не совсем понял о чем тут имеется ввиду. 
стр. №624-627 как раз проверяют если кол-во завершенных глав соответствует кол-ву глав в курсе то COMPLETED & 200. В противном случае 403 ?

2024-01-31 06:35 UTC, Leontiev93 commented on src/tests/test_courses.py
> +        if len(user_completed_chapters) == len(total_completed_chapters):
Я пробовал создавать фабрику с пройдёнными курсами возвращала True. Посчитал не нужным ее оставлять. 
Что по итогу нужно сделать ?

2024-01-31 21:08 UTC, Di0niz requested changes

2024-01-31 21:08 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +        user_completed_chapters = user.user_chapter_status.all().filter(progress=2, chapter__course=kwargs["pk"])
вместо магических значения нужно использовать константы

2024-01-31 21:08 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +        if len(user_completed_chapters) == len(total_completed_chapters):
Два запроса к БД замени на один, пусть БД сравнивает уроки

Сравнение длины не гарантирует, что студент прошел все требуемые уроки

например, студент прошел 7 из 8 уроков, 5 уроков убрали, а 4 добавили - получиться рассинхрон между прогрессом студента и уроками.

2024-02-01 19:27 UTC, Leontiev93 commented on src/tests/test_courses.py
> +            assert response.status_code == status.HTTP_403_FORBIDDEN
Это то что нужно было сделать ? 
`    def test_course_completion_endpoint(self, user_client, user):
        """
        Тест эндпоинта завершения курса.

        Проверяем, что при завершении курса, пользователь получает статус COMPLETED.
        Проверяем что курс можно завершить только с завершенными главами, в противном случае получаем 403.
        """
        course = CourseWith2Chapters()
        url = reverse("courses-complete", kwargs={"pk": course.id})
        url_course = reverse("courses-detail", kwargs={"pk": course.id})
        response = user_client.post(url)
        assert response.status_code == status.HTTP_404_NOT_FOUND
        subscription = SubscriptionFactory(user=user, course=course)
        response = user_client.post(url)
        assert response.status_code == status.HTTP_403_FORBIDDEN
        response_course = user_client.get(url_course)
        lessons = Lesson.objects.filter(chapter__course=course)
        for lesson in lessons:
            lesson.finish(subscription)
        response = user_client.post(url)
        response_course = user_client.get(url_course)
        assert response.status_code == status.HTTP_200_OK
        assert response_course.json()["user_status"] == Subscription.Status.COMPLETED`

2024-02-01 19:30 UTC, Leontiev93 commented on src/lizaalert/courses/views.py
> +        if len(user_completed_chapters) == len(total_completed_chapters):
Сравнение по кол-ву завершенных глав гарантирует что студент прошел весь курс. 
Сделал вот так, сейчас пытаюсь сделать проверку внутри метода finish  
`    def complete(self, request, **kwargs):
        """
        Завершить курс для пользователя.

        Данное событие вызывает сигнал завершения курса.
        """
        user = self.request.user
        try:
            course = get_object_or_404(Course, **kwargs)
            subscription = get_object_or_404(Subscription, course=course, user=user)
        except ValueError:
            raise BadRequestException({"detail": "Invalid id."})
        user_completed_chapters = user.subscriptions.filter(chapter_progress__chapter__course_id=kwargs['pk']).count()
        total_completed_chapters = course.chapters.all().count()
        if user_completed_chapters == total_completed_chapters:
            course.finish(subscription)
            # Отправить сигнал для получения ачивок
            course.get_achievements(course, user)
            return Response(status=status.HTTP_200_OK)
        return Response(
            {"message": "Пользователь не прошел все уроки/главы"},
            status=status.HTTP_403_FORBIDDEN,
        )`

2024-02-01 20:41 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +        total_completed_chapters = course.chapters.all()
нет, два запрос к бд заменить на один

2024-02-01 20:52 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +        if len(user_completed_chapters) == len(total_completed_chapters):
Сравнение по кол-ву завершенных глав не может гарантировать:

len([1,2,3]) == len([2,3,4])

2024-02-01 21:13 UTC, Leontiev93 commented on src/lizaalert/courses/views.py
> +        if len(user_completed_chapters) == len(total_completed_chapters):
Если в курсе 3 главы то не важно в каком порядке они идут. это гарантирует окончание курса

2024-02-01 21:13 UTC, Leontiev93 commented on src/lizaalert/courses/views.py
> +        if len(user_completed_chapters) == len(total_completed_chapters):
Главы завершаются только по завершению уроков

2024-02-02 00:03 UTC, cosmofactory requested changes

2024-02-02 00:03 UTC, cosmofactory commented on src/lizaalert/courses/views.py
> +        return Response({"message": message}, status=status_code)
Файл views.py здесь трогать вообще не надо, метод finish() должен делать все сам, а не возвращать что то

2024-02-02 00:03 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +        total_chapters = self.chapters.all().count()
если хочешь посчитать все главы курса, то это будет 
`self.chapters.count()`
.all() здесь создает дополнительную нагрузку на БД

2024-02-02 00:03 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +        if user_completed_chapters == total_chapters:
Давай сделаем по другому, я забыл, что у нас у главы нет статуса опубликована/не опубликована, так что обратимся к урокам. Постараемся понять прошли ли мы курс за один запрос и ничего не сравнивая в коде Джанго. 

Нам надо понять, одну вещь - существуют ли опубликованные уроки, которые мы не проходили, если таких нет, значит курс пройдет, если таковы в наличии, значит курс не пройдет. Вот как должен выглядеть такой запрос:

```
uncompleted_lessons = Lesson.objects.filter(
    chapter__course=self, 
    status=Lesson.LessonStatus.PUBLISHED,
    lesson_progress__subscription=subscription,
).exclude(id__in=LessonProgressStatus.objects.filter(
            subscription=subscription, progress=LessonProgressStatus.ProgressStatus.FINISHED
        ).values_list("lesson_id", flat=True)).exists()
```

Что мы в нем делаем:
- выбираем все уроки, которые находятся в этом курсе, при этом опубликованы, при этом принадлежат нашей подписке
- исключаем из них те уроки, которые находятся в запросе к LessonProgressStatus
- к запросу LessonProgressStatus мы добавляем параметр values_list и flat=True, чтобы получить только id уроков в виде списка, а не в виде списка кортежей
- проверяем, существует ли такой урок, если существует, значит курс не пройдет

2024-02-02 00:03 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +        return (message, status.HTTP_403_FORBIDDEN)
Не должно быть никаких return. 
Если курс не пройдет, то метод выбает ошибку. 
Вместо return должен быть кастомный raise ProgressNotFinishedException()

https://www.django-rest-framework.org/api-guide/exceptions/

2024-02-02 00:03 UTC, cosmofactory commented on src/tests/test_courses.py
> +        assert response.status_code == status.HTTP_404_NOT_FOUND
В аннотации к тесту не написано, что мы здесь проверяем.

2024-02-02 00:03 UTC, cosmofactory commented on src/tests/test_courses.py
>          response_course = user_client.get(url_course)
Строка 636 и строка 631, зачем нам два раза response_course?

2024-02-03 14:15 UTC, cosmofactory approved these changes

2024-02-03 14:15 UTC, cosmofactory commented on src/tests/test_courses.py
> +        response_course = user_client.get(url_course)
Строка 632 и строка 637, в чем их разница, почему их две?

2024-02-04 11:46 UTC, cosmofactory approved these changes

2024-02-04 14:15 UTC, Di0niz requested changes

2024-02-04 14:15 UTC, Di0niz commented on src/lizaalert/courses/models.py
>          progress_status, created = Subscription.objects.get_or_create(
Подписка уже есть, давай просто установим состояние для текущей

subscription.finish()


и в этом методе будет завершение подписки

2024-02-04 14:15 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +        return Response({"message": "Курс успешно завершен"}, status=status.HTTP_200_OK)
Добавь для таких сообщение сериализатор, чтобы всегда сообщения в одном формате

Изменение ответа нужно поддержать в схеме сваггера

2024-02-04 14:15 UTC, Di0niz commented on src/tests/test_courses.py
> +                    lesson.finish(subscription)
Главы тоже завершить надо

2024-02-05 18:47 UTC, Di0niz requested changes

2024-02-05 18:47 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        self.save()
лучше явно указать метод finish (чтобы разработчик не думал, какой статус надо установить)

```suggestion
    def finish(self, status):
        """Изменение статуса подписки на крус."""
        self.status = Subscription.Status.COMPLETED
        self.save()
```

2024-02-05 19:04 UTC, Di0niz approved these changes

2024-02-05 19:05 UTC, merged