TM-36 Навигация по курсам/главам/урокам
Studio-Yandex-Practicum/lizaalert_backend pull request #318
Opened 2024-01-31 13:19 UTC by InAnotherLife

В карточку курса добавил отображение ссылки на главу

2024-01-31 21:05 UTC, Di0niz requested changes

2024-01-31 21:05 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +    )
поля created и updated автозаполняемые

```suggestion
    fields = (
        "get_chapter_link",
        "order_number",
        "title",
        "deleted_at",
    )
```

2024-01-31 21:05 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +    get_chapter_link.short_description = "Ссылка"
по сути этот объект является главой

```suggestion
    get_chapter_link.short_description = "Глава"
```

2024-02-01 15:13 UTC, InAnotherLife commented on src/lizaalert/courses/admin.py
> +    )
Может быть fields вообще убрать?

2024-02-01 15:24 UTC, Di0niz approved these changes

2024-02-01 15:50 UTC, merged