MIL-66 Bugfix 500 ошибка для неопубликованного урока
Studio-Yandex-Practicum/lizaalert_backend pull request #329
Opened 2024-02-01 16:04 UTC by cosmofactory

2024-02-01 19:01 UTC, ilin-art approved these changes

2024-02-04 14:11 UTC, Di0niz requested changes

2024-02-04 14:11 UTC, Di0niz commented on src/lizaalert/courses/permissions.py
> +            if current_lesson and (current_lesson.ordering >= obj.ordering):
Такой способ сравнения возможен только в рамках главы. Нужно еще главы проверить

2024-02-04 15:06 UTC, Di0niz approved these changes

2024-02-05 13:41 UTC, merged