TM-45 Bugfix Ошибка 500 в разделе "Изменить курс" при создании главы курса
Studio-Yandex-Practicum/lizaalert_backend pull request #346
Opened 2024-02-09 08:06 UTC by InAnotherLife

Починил баг. Баг связан с тем что, в админке при создании главы автоматически не заполняются поля user_created и user_modifier.

Также сразу предлагаю подставить два костыля:
1) У главы для поля title установлены параметры null=True, blank=True, поэтому ссылка для главы без названия будет отображаться как None. Предлагаю проверять поле title главы и если оно = None, то в ссылке прописывать title = "Нет названия".
2) В админке при создании новой главы ссылка для этой главы также будет отображаться, как None. Предлагаю проверять поле id главы и если оно = None, то возвращать не ссылку, а текст "Новая глава".

2024-02-12 14:19 UTC, Di0niz requested changes

2024-02-12 14:19 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        return format_html('<a href="{}">{}</a>', url, title)
```suggestion
        id = obj.id
        title = obj.title
        url = reverse("admin:courses_chapter_change", args=(object.id,))
        if object.id is None:
            return "Новая глава"
        if object.title is None:
            title = "Нет названия"
        return format_html('<a href="{}">{}</a>', url, object.title)
```

2024-02-12 14:19 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        "user_modifier",
эти поля можно не выводить, они заполняются автоматически

2024-02-12 14:19 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        if id is None:
проверка на id должна быть до получения url

2024-02-12 14:19 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +            title = "Нет названия"
если пустая строка, то тоже лучше выполнить называние

```suggestion
        title = title or "Нет названия"
```

2024-02-12 14:19 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        if id is None:
если нет id, то лучше тоже выводить "Нет названия"

2024-02-16 11:37 UTC, Di0niz requested changes

2024-02-16 11:37 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        if not id:
по сути нет названия, когда заголовок не заполнен

```suggestion
```

2024-02-16 11:37 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +                chapter.save()
нужно избежать записи в цикле

2024-02-16 15:35 UTC, InAnotherLife commented on src/lizaalert/courses/admin.py
> +        if not id:
Если не проверять id главы и не делать return "Нет названия", то при добавлении новой главы будет формироваться ссылка http://0.0.0.0:8000/admin/courses/chapter/None/change/

2024-02-16 15:37 UTC, InAnotherLife commented on src/lizaalert/courses/admin.py
> +                chapter.save()
Глава в админке имеет модель типа inline, соответственно в админке можно добавлять несколько глав одновременно. Поэтому нужно в цикле перебрать каждую главу и установить для нее user_created и user_modifier

2024-02-21 11:50 UTC, Di0niz requested changes

2024-02-21 11:50 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        return format_html('<a href="{}">{}</a>', url, title)
ок, давай title определим в одном месте

```suggestion
        title = obj.title or "Нет названия"
        if not (id := obj.id):
            return format_html('<span>{}</span>', title)
        return format_html('<a href="{}">{}</a>', reverse("admin:courses_chapter_change", args=(id,)), title)
```

2024-02-21 11:50 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +                chapter.save()
для обработки список значений, используются функции bulk_update, bulk_create

2024-02-21 11:50 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +                chapter.save()
```suggestion
            chapters = formset.save(commit=False)
            for chapter in chapters:
                if not chapter.id:
                    chapter.user_created = request.user
                chapter.user_modifier = request.user
    Chapters.objects.bulk_create(filter(lamdba chapter : not chapter.id: , chapters))
    Chapters.objects.bulk_update(filter(lamdba chapter: bool(chapter.id): , chapters))
```

2024-02-21 14:49 UTC, InAnotherLife commented on src/lizaalert/courses/admin.py
> +                chapter.save()
В методе save_formset обязательно нужно вызвать метод save_m2m() перед возвратом, иначе формы не будут иметь атрибута new_objects и будет ошибка:

File "/usr/local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1061, in construct_change_message
	return construct_change_message(form, formsets, add)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 518, in construct_change_message
	for added_object in formset.new_objects:
AttributeError: 'CourseFaqFormFormSet' object has no attribute 'new_objects'

2024-02-21 17:52 UTC, InAnotherLife commented on src/lizaalert/courses/admin.py
> +                chapter.save()
При использовании bulk_create и bulk_update у главы автоматически не заполняется поле order_number. Если я явно вызываю метод set_ordering из order_number_mixin, то для новых глав устанавливается одинаковый order_number.

2024-02-26 15:55 UTC, InAnotherLife commented on src/lizaalert/courses/admin.py
> +                chapter.save()
Как меньшее из зол, оставляем добавление объектов в БД через цикл.

2024-02-26 17:29 UTC, Di0niz approved these changes

2024-02-28 15:19 UTC, merged