MIL-76 создать приложение Homeworks и модель Homework
Studio-Yandex-Practicum/lizaalert_backend pull request #353
Opened 2024-02-09 14:00 UTC by cosmofactory

Создана модель и приложение, написана базовая фабрика.

2024-02-09 19:02 UTC, Leontiev93 approved these changes

2024-02-09 19:02 UTC, Leontiev93 commented on src/lizaalert/homeworks/models.py
> +    status = models.IntegerField(
Думаю в таком случаю лучше применять поля типа. 
PositiveSmallIntegerField

2024-02-09 19:02 UTC, Leontiev93 commented on src/tests/factories/homeworks.py
> +    status = factory.fuzzy.FuzzyInteger(0, 5)
Возможно тут стоит посмотреть в сторону FuzzyChoice
[https://factoryboy.readthedocs.io/en/stable/fuzzy.html#factory.fuzzy.FuzzyChoice](url)

2024-02-10 19:03 UTC, Leontiev93 commented on src/lizaalert/homeworks/models.py
> +    text = models.CharField(verbose_name="Текст задания", max_length=10000)
Нужно добавить поле с описание того что нужно сделать в домашнем задании второе поле оставить под выполнение  домашнего задания и сделать bank=true null=true

2024-02-11 17:33 UTC, Leontiev93 requested changes

2024-02-11 17:33 UTC, Leontiev93 commented on src/lizaalert/homeworks/models.py
> +    lesson = models.OneToOneField(Lesson, on_delete=models.CASCADE, verbose_name="Урок")
Если использовать данный тип поля то можно создать всего 1 домашнее задание . 
по такой логике больше 1 пользователя не может выполнять домашнее задание.

2024-02-11 20:30 UTC, Leontiev93 approved these changes

2024-02-12 06:42 UTC, Leontiev93 commented on src/lizaalert/homeworks/models.py
> +    text = models.CharField(verbose_name="Текст задания", max_length=10000)
Если пользователь только перешел к выполнению домашней работы, экземпляр модели будет создаваться сразу с статусом черновик ? 
тогда необходимо поле текст сделать null=True и blank=True 
Или это будет пред заполненная форма одним пустым полем text и мы будем сохранять ее в базу только после отправки ?

2024-02-12 14:15 UTC, Di0niz approved these changes

2024-02-12 14:15 UTC, Di0niz commented on src/lizaalert/homeworks/models.py
> +    text = models.CharField(verbose_name="Текст задания", max_length=10000)
домашка не может быть в неизвестном статусе. если разработчик при создании не указал статус, то будет draft.

2024-02-12 14:15 UTC, Di0niz commented on src/tests/test_homeworks.py
> +        assert obj == homework
тест проверяет работу библиотек. можно без теста

2024-02-12 14:17 UTC, merged