MIL-77 Описать viewsets, serializers, permissions для Homework (В РАБОТЕ)
Studio-Yandex-Practicum/lizaalert_backend pull request #355
Opened 2024-02-13 19:03 UTC by Leontiev93

Задача в работе.

2024-02-13 19:27 UTC, cosmofactory requested changes

2024-02-13 19:27 UTC, cosmofactory commented on src/lizaalert/homeworks/urls.py
> +    # path("lessons/<int:lesson_id>/quiz/answer/", QuizDetailAnswerView.as_view(), name="quiz-answer"),
закомментированный код надо убрать

2024-02-13 19:27 UTC, cosmofactory commented on src/lizaalert/homeworks/urls.py
> +    path("homeworks/", HomeworkViewSet.as_view(), name="homework"),
мы используем здесь модель, зачем нам as_view?

2024-02-13 19:27 UTC, cosmofactory commented on src/lizaalert/homeworks/views.py
> +class HomeworkException(APIException):
Исключения должны быть в отдельном модуле

2024-02-13 19:27 UTC, cosmofactory commented on src/lizaalert/homeworks/views.py
> +    Класс дял отображение всех домашних работ одного преподавателя.
```suggestion
    Класс для отображения всех домашних работ одного преподавателя.
```

2024-02-13 19:27 UTC, cosmofactory commented on src/lizaalert/homeworks/views.py
> +class HomeworkException(APIException):
И название исключения должно быть более говорящее о себе

2024-02-13 19:27 UTC, cosmofactory commented on src/lizaalert/homeworks/views.py
> +    serializer_class = HomeworkSerializer
добавить permission classes

2024-02-13 19:27 UTC, cosmofactory commented on src/lizaalert/homeworks/views.py
> +class HomeworkDetailViewSet(generics.RetrieveAPIView, generics.CreateAPIView):
давай это сделаем на viewset, а не на view

2024-02-14 18:55 UTC, cosmofactory requested changes

2024-02-14 18:55 UTC, cosmofactory commented on src/lizaalert/homeworks/serializers.py
> +class HomeworkDetailSerializer(HomeworkSerializer):
Этот сериализатор нам наверное не пригодится

2024-02-14 18:55 UTC, cosmofactory commented on src/lizaalert/homeworks/urls.py
> +]
```suggestion
from lizaalert.homeworks.views import HomeworkViewSet

urlpatterns = [
    path('lessons/<int:lesson_id>/homework/', HomeworkViewSet.as_view({
        'get': 'retrieve', 'post': 'create'}), name='lesson-homework-detail'),
]

```
К сожалению, из-за того что у нас нестандартные ручки, здесь не получится ограничится роутером, придется сделать немного танцев с бубнами, чтобы наши эндпоинты имели вид:
lesson/id/homework - retrieve
lesson/id/homework - post

2024-02-14 18:55 UTC, cosmofactory commented on src/lizaalert/homeworks/views.py
> +):
Давай посмотрим на миксины:
Create - да, нам надо создавать
Retrieve - да, нам надо получать дз
List? У нас нет на данный момент ситуации когда нам надо получить список дз, так что его можно убрать

2024-02-14 18:55 UTC, cosmofactory commented on src/lizaalert/homeworks/views.py
> +        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)
```suggestion
class HomeworkViewSet(mixins.CreateModelMixin, mixins.RetrieveModelMixin, viewsets.GenericViewSet):

    serializer_class = HomeworkSerializer
    permission_classes = (IsAuthenticated,)
    lookup_field = 'lesson_id'
    queryset = Homework.objects.all()

    def perform_create(self, serializer):
        lesson_id = self.kwargs.get('lesson_id')
        subscription = get_object_or_404(Subscription, user=self.request.user, course__chapters__lessons__id=lesson_id)
        homework, created = Homework.objects.get_or_create(
            lesson_id=lesson_id,
            subscription=subscription,
            defaults={'reviewer': subscription.cohort.teacher}
        )
        if not created:
            for attr, value in serializer.validated_data.items():
                setattr(homework, attr, value)
            homework.save()
        serializer.instance = homework
        return super().perform_create(serializer)
```

очень много кода, большую часть которого за нас может сделать джанго, давай попробуем сократить
при необходимости с небольшим редактированием код выше делает ту работу, которая от нас требуется при получении и отправлении домашнего задания

2024-02-15 11:33 UTC, cosmofactory requested changes
В модели Homework поменяй пожалуста статусы:

```
    class ProgressionStatus(models.IntegerChoices):
        DRAFT = 0, "Черновик"
        SUBMITTED = 1, "Отправлено"
        IN_REVIEW = 2, "На проверке"
        APPROVED = 3, "Одобрено"
        REJECTED = 4, "Отклонено"
        CANCELLED = 5, "Отменено"
```

вместо цифр напиши буквеныне значения, draft, approved etc
это будет уже textChoices вмест IntegerChoices

2024-02-15 11:33 UTC, cosmofactory commented on src/lizaalert/homeworks/migrations/0002_alter_homework_lesson.py
> +    ]
Нам еще надо добавить в модель Lesson тип урока Homework

2024-02-15 11:33 UTC, cosmofactory commented on src/tests/test_homeworks.py
> +        course.chapters.add(chapter)
```suggestion
        course = CourseWith2Chapters()
        lesson = Lesson.objects.filter(chapter__course=lesson.chapter.course)
        lesson.lesson_type = Lesson.LessonType.HOMEWORK
        lesson.save()
```

2024-02-15 11:33 UTC, cosmofactory commented on src/tests/test_homeworks.py
> +        _ = SubscriptionFactory(course=course, user=user)
```suggestion
        _ = SubscriptionFactory(course=course, user=user)
        draft_data = {"text": text, "status": 0}
        submit_data = {"text": text, "status": 1}
        #  И далее посмотреть на то как работает наш бэк в зависимотсти от передаваемых данных
```

2024-02-15 11:33 UTC, cosmofactory commented on src/tests/test_homeworks.py
> +        assert response_get_homework.json()["text"] == text
Не хватает проверки:
1. Повторное отправление черновика меняет предыдущий черновик
2. Отправление черновика на проверку меняет статус записи в БД на SUBMITTED

2024-02-15 11:33 UTC, cosmofactory commented on src/lizaalert/homeworks/serializers.py
> +        )
Добавим еще один сериализатор:

```
class EmptyHomeworkSerializer(serializers.Serializer):
    status = serializers.ChoiceField(choices=Homework.ProgressionStatus, default=Homework.ProgressionStatus.DRAFT)
    text = serializers.CharField(default='')

```

2024-02-15 11:33 UTC, cosmofactory commented on src/lizaalert/homeworks/views.py
> +        return obj
Давай не будем передавать на фронт ошибку, а передадим пустое задание. 
```suggestion
    def retrieve(self, request, *args, **kwargs):
        try:
            instance = get_object_or_404(Homework, **kwargs)
            serializer = self.get_serializer(instance)
        except Http404:
            serializer = EmptyHomeworkSerializer()
        return response.Response(serializer.data, status=status.HTTP_200_OK)
```

2024-02-15 21:00 UTC, cosmofactory approved these changes
Добей тест и от меня больше нет замечаний 
И разберись почему у тебя старые тесты падают

2024-02-15 21:00 UTC, cosmofactory commented on src/tests/test_homeworks.py
> +        assert response_get_homework.json()["text"] == text_change == response_submitted.json()["text"]
Этот код можно сделать намного более читабельным и сократить, оберни это в функцию которая будет проверять ожидаемый ответ (похожие решения есть в тестах курсов)

2024-02-15 21:00 UTC, cosmofactory commented on src/lizaalert/homeworks/exceptions.py
> +    default_detail = "Некорректный запрос"
Это исключение уже потеряло актуальность

2024-02-16 11:34 UTC, Di0niz commented
Нужно сделать rebase после изменений в https://github.com/Studio-Yandex-Practicum/lizaalert_backend/pull/361

2024-02-18 08:59 UTC, Di0niz requested changes

2024-02-18 08:59 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        HOMEWORK = "Homework", "Домашняя работа"
статусы в базе нужно хранить с типом число

2024-02-18 08:59 UTC, Di0niz commented on src/lizaalert/homeworks/serializers.py
> +    status = serializers.ChoiceField(choices=Homework.ProgressionStatus)
здесь добавить меппинг между значением статуса и его представлением для фронта

2024-02-18 08:59 UTC, Di0niz commented on src/lizaalert/homeworks/migrations/0002_alter_homework_lesson.py
> +class Migration(migrations.Migration):
объедини файлы с миграциями

2024-02-18 08:59 UTC, Di0niz commented on src/lizaalert/homeworks/serializers.py
> +    status = serializers.ChoiceField(choices=ProgressionStatus)
на фронт нужно отправлять преобразованные числа в строки: approve, draft

2024-02-18 12:12 UTC, Leontiev93 commented on src/lizaalert/homeworks/serializers.py
> +    status = serializers.ChoiceField(choices=Homework.ProgressionStatus)
Не ясно принимать в числах а передавать обратно в буквах ?
или что имеется ввиду ?

2024-02-18 12:13 UTC, Leontiev93 commented on src/lizaalert/courses/models.py
> +        HOMEWORK = "Homework", "Домашняя работа"
Статусы уроков хранятся в базе в числах 
![image](https://github.com/Studio-Yandex-Practicum/lizaalert_backend/assets/107325873/9f95067f-7471-4d83-9b4c-49887acc2ede)

2024-02-19 11:38 UTC, cosmofactory requested changes

2024-02-19 11:38 UTC, cosmofactory commented on src/lizaalert/homeworks/migrations/0004_alter_homework_status.py
> +    ]
все равно много миграций, надо откатить бд, удалить старые миграции, которых нет на проде и сделать снова

2024-02-19 11:38 UTC, cosmofactory commented on src/lizaalert/homeworks/migrations/0004_alter_homework_status.py
> +    ]
1. python manage.py migrate courses 0002_alter.....
2. Удаляем 0003, 0004, сквошить тоже на надо, должна быть 0001_init
3. python manage.py makemigrations
4. python manage.py migrate

2024-02-19 11:38 UTC, cosmofactory commented on src/lizaalert/homeworks/serializers.py
> +        return ret
Слишком сложный код для такой простой вещи, который к тому же возвращает русский вариант написания.
```suggestion
    def get_status(self, obj):
        return obj.get_status_display().lower()
```
Переименуй ProgressionStatus русское описание в английское и примени этот метод тогда.

2024-02-20 13:22 UTC, cosmofactory reviewed
моя ветка поменялась, там теперь не декоратор

2024-02-21 10:34 UTC, Di0niz requested changes

2024-02-21 10:34 UTC, Di0niz commented on src/lizaalert/homeworks/migrations/0001_initial.py
> +class Migration(migrations.Migration):
сделай rebase по миграциям, на проде уже 0001 и 0002 миграции

2024-02-21 10:34 UTC, Di0niz commented on src/lizaalert/homeworks/views.py
> +            homework.save()
при обновлении домашки, правильнее указывать какие поля сохраняешь

2024-02-21 10:34 UTC, Di0niz commented on src/lizaalert/homeworks/views.py
> +        return super().perform_create(serializer)
serializer.save() выполняет запись объекта, при этом объект уже сохранен.

проверь количество запросов при сохранении домашки

2024-02-21 10:34 UTC, Di0niz commented on src/tests/factories/courses.py
> +    lesson_type = Lesson.LessonType.HOMEWORK
сделай rebase

2024-02-21 10:35 UTC, Di0niz requested changes

2024-02-21 10:35 UTC, Di0niz commented on src/tests/factories/courses.py
> +    lesson_type = Lesson.LessonType.HOMEWORK
при создании домашки указажи тип урока

2024-02-21 10:38 UTC, Leontiev93 commented on src/lizaalert/homeworks/migrations/0001_initial.py
> +class Migration(migrations.Migration):
Сделал ребейс от прода у меня тоже 2 миграции

2024-02-21 10:39 UTC, Leontiev93 commented on src/lizaalert/homeworks/migrations/0001_initial.py
> +class Migration(migrations.Migration):
![image](https://github.com/Studio-Yandex-Practicum/lizaalert_backend/assets/107325873/325a8052-c6b0-498f-b976-80c3b5042c24)

2024-02-21 11:32 UTC, Di0niz requested changes

2024-02-21 11:32 UTC, Di0niz commented on src/tests/factories/courses.py
> +    lesson_type = Lesson.LessonType.HOMEWORK
```suggestion
```

2024-02-21 19:05 UTC, Leontiev93 commented on src/lizaalert/homeworks/views.py
> +        return super().perform_create(serializer)
Да действительно происходит 2 обращения к БД. 
![image](https://github.com/Studio-Yandex-Practicum/lizaalert_backend/assets/107325873/caf33c86-7ba9-413b-9563-904bc1d54563)

2024-02-21 19:06 UTC, Leontiev93 commented on src/lizaalert/homeworks/views.py
> +        return super().perform_create(serializer)
В этом случае происходит 1 запрос. 
![image](https://github.com/Studio-Yandex-Practicum/lizaalert_backend/assets/107325873/e24e5dc2-c989-4822-88bc-254762f655e0)

2024-02-22 09:42 UTC, cosmofactory approved these changes

2024-02-22 20:06 UTC, Di0niz requested changes

2024-02-22 20:06 UTC, Di0niz commented on src/lizaalert/homeworks/views.py
> +        homework, created = Homework.objects.get_or_create(
здесь переопределяется стандартный способ получения объекта

посмотри как устроен get_object и туда перенеси создание и получение объекта

2024-02-25 12:47 UTC, Leontiev93 commented on src/lizaalert/homeworks/views.py
> +        homework, created = Homework.objects.get_or_create(
get_object не используют  классы mixins.CreateModelMixin . Нет смысла его переопределять. 
Целесообразней переопределить метод perform_create впрочем как и было сделано. 
Если необходимо внести дополнительные изменения прошу расписать немного подробней.

2024-02-26 15:51 UTC, Di0niz requested changes

2024-02-26 15:51 UTC, Di0niz commented on src/lizaalert/homeworks/views.py
> +            homework.text = serializer.validated_data.get("text")
```suggestion
     homework.status = serializer.validated_data.get("status")
     homework.text = serializer.validated_data.get("text")
```

2024-02-26 15:51 UTC, Di0niz commented on src/lizaalert/homeworks/views.py
> +        serializer.save()
```suggestion
        homework.save()
        serializer.instance = homework
```

2024-02-28 07:32 UTC, Di0niz requested changes
осталось с фабрикой поправить
тест очень сложный получился, попробуй упростить логику или разделить на части

2024-02-28 07:32 UTC, Di0niz commented on src/tests/factories/users.py
> +class UserRoleFactory(factory.django.DjangoModelFactory):
добавь создание UserRole в фабрику пользователя, чтобы по умолчанию был волотером

2024-02-28 15:09 UTC, Di0niz approved these changes

2024-02-28 15:11 UTC, merged