TM-47 hiden courses & tests
Studio-Yandex-Practicum/lizaalert_backend pull request #359
Opened 2024-02-14 13:59 UTC by ilin-art

Создание скрытых курсов

2024-02-14 19:17 UTC, cosmofactory requested changes

2024-02-14 19:17 UTC, cosmofactory commented on src/tests/test_courses.py
> +        hidden_course = CourseFactory(is_hidden=True)
С этой фабрикой тест упадет в связи с последними изменениями на проде. 
Надо фабрику Курса с Когортой, типа CourseWith2Chapters() или CourseWithFutureCohortFactory()

2024-02-16 10:34 UTC, Di0niz requested changes

2024-02-16 10:34 UTC, Di0niz commented on src/lizaalert/courses/migrations/0022_auto_20240211_2217.py
> +        ('courses', '0021_Created_model_cohort'),
сделай обновление из текущей ветки (последняя ревизия 25)

2024-02-16 10:34 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +    is_hidden = models.BooleanField(verbose_name="скрытый курс", default=False)
добавить новое значение в CourseStatus "hidden" - скрытый

2024-02-16 10:34 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +                )
```suggestion
            queryset = (
                Course.objects.filter(
                    Q(
                        status=Course.CourseStatus.PUBLISHED
                    )
                    | Q(
                        status=Course.CourseStatus.HIDDEN,
                        id__in=Subquery(
                            Subscription.objects.filter(user=user, course_id=OuterRef("id")).values("course")
                        ),
                    )
                )
```

2024-02-16 10:34 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +        ).annotate(**base_annotations)
должен остаться один запрос (тот который выше)

2024-02-16 10:34 UTC, Di0niz commented on src/tests/test_courses.py
> +        hidden_course = CourseFactory(is_hidden=True)
здесь просто укажи новый статус

2024-02-16 10:34 UTC, Di0niz commented on src/tests/test_courses.py
> +        _ = SubscriptionFactory(course=hidden_course, user=user)
или

subscription = SubscriptionFactory(course__status=.HIDDEN, user=user)

2024-02-16 13:50 UTC, cosmofactory commented on src/lizaalert/courses/views.py
> +        ).annotate(**base_annotations)
Нет, этот запрос тоже должен остаться. Он возвращает queryset для неавторизованного пользователя.

2024-02-19 13:59 UTC, cosmofactory approved these changes
Что то как то странно ветка dev подтянулась, эти изменения перезапишут все остальные изменения 
Надо как то по другому обновить текущую ветку

2024-02-19 13:59 UTC, cosmofactory commented on src/lizaalert/courses/views.py
> +            return queryset
```suggestion

            return (
                Course.objects.filter(
                    Q(status=Course.CourseStatus.PUBLISHED)
                    | Q(
                        status=Course.CourseStatus.HIDDEN,
                        id__in=Subquery(
                            Subscription.objects.filter(user=user, course_id=OuterRef("id")).values("course")
                        ),
                    )
                )
                .annotate(**base_annotations, **users_annotations)
                .prefetch_related(
                    Prefetch("chapters", queryset=chapters_with_progress),
                    Prefetch("chapters__lessons", queryset=lessons_with_progress),
                )
            )
```

2024-02-26 17:28 UTC, Di0niz approved these changes
поправь тест и мержи

2024-02-26 17:28 UTC, Di0niz commented on src/tests/test_courses.py
> +        assert hidden_course.title not in [course["title"] for course in response.json()["results"]]
заголовок явно не задаешь, чтобы его проверять
найди курс по id

```suggestion
        assert hidden_course.id not in set(course["id"] for course in response.json()["results"])
```

2024-02-27 15:07 UTC, merged