MIL-81 Завершить урок можно только после завершения домашнего задания (или другого контента.)
Studio-Yandex-Practicum/lizaalert_backend pull request #361
Opened 2024-02-15 14:09 UTC by cosmofactory

2024-02-16 10:26 UTC, Di0niz requested changes

2024-02-16 10:26 UTC, Di0niz commented on src/lizaalert/courses/utils.py
> +def check_finished_content(lesson_type=()):
Опасно присваивать объекты в качестве дефолтных значений

```suggestion
def check_finished_content(lesson_type=None):
```

2024-02-16 10:26 UTC, Di0niz commented on src/lizaalert/courses/utils.py
> +            lesson = args[0]
в декораторе явно задать параметры lesson, subscription

2024-02-16 10:26 UTC, Di0niz commented on src/lizaalert/homeworks/models.py
> +class ProgressionStatus(models.TextChoices):
нужно оставить прогресс в домашке

2024-02-16 10:26 UTC, Di0niz commented on src/lizaalert/homeworks/models.py
> +class ProgressionStatus(models.TextChoices):
тип статуса менять не надо (по прежнему храним в базе число)

2024-02-16 10:26 UTC, Di0niz commented on src/lizaalert/homeworks/models.py
> +        verbose_name="Статус", choices=ProgressionStatus.choices, default=ProgressionStatus.DRAFT, max_length=20
тип не меняем

2024-02-16 10:26 UTC, Di0niz commented on src/tests/test_courses.py
> +                assert subscription.lesson_progress.get(lesson=lesson).progress == expected_status
явно указать таблицу (без related)

2024-02-16 10:45 UTC, cosmofactory commented on src/lizaalert/homeworks/models.py
> +class ProgressionStatus(models.TextChoices):
Прогресс оставили вынесенным вне Домашки, тип статуса вернули на число.

2024-02-16 14:19 UTC, Di0niz requested changes

2024-02-16 14:19 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +    @check_finished_content(lesson_type=[LessonType.HOMEWORK])
выглядит так, что это должен быть параметр миксина (сделай без переопределения finish)

2024-02-16 14:19 UTC, Di0niz commented on src/lizaalert/courses/utils.py
> +def check_finished_content(lesson_type=None):
перенеси в mixin, чтобы не требовалось параллельного использования миксина и декоратора (при этом, одно без другого не работает)

2024-02-16 14:19 UTC, Di0niz commented on src/tests/factories/homeworks.py
> +    status = ProgressionStatus.DRAFT
в модели уже указано дефолтное значение DRAFT

```suggestion
```

2024-02-16 14:19 UTC, Di0niz commented on src/tests/test_courses.py
> +        homework = HomeworkFactory()
настрой HomeworkFactory, чтобы урок создавался с нужным типом Lesson.LessonType.HOMEWORK

2024-02-20 10:11 UTC, Di0niz requested changes

2024-02-20 10:11 UTC, Di0niz commented on src/lizaalert/courses/utils.py
> +def check_finished_content(lesson, subscription, lesson_type=None):
функция слишком много делает: замени на is_finish , а в другом месте опиши что делать

2024-02-20 10:11 UTC, Di0niz commented on src/tests/factories/courses.py
> +class HomeworkLessonFactory(LessonFactory):
можно не создавать новый класс

2024-02-20 10:11 UTC, Di0niz commented on src/tests/factories/homeworks.py
> +    lesson = factory.SubFactory(HomeworkLessonFactory)
в subfactory передай новый параметр для lesson

2024-02-20 13:29 UTC, Di0niz requested changes

2024-02-20 13:29 UTC, Di0niz commented on src/lizaalert/courses/utils.py
> +            raise ProgressNotFinishedException("Необходимый контент урока не пройден.")
```suggestion
    if lesson.lesson_type in lesson_type:
        return (
            getattr(lesson, lesson.lesson_type.lower())
            .filter(subscription=subscription, status=ProgressionStatus.APPROVED, required=True)
            .exists()
        )
        return False
```

2024-02-20 13:29 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        check_finished_content(self, subscription, lesson_type=[Lesson.LessonType.HOMEWORK])
```suggestion
        if not check_finished_content(self, subscription, lesson_type=[Lesson.LessonType.HOMEWORK]):
             raise ProgressNotFinishedException("Необходимый контент урока не пройден.")
```

2024-02-20 14:45 UTC, Di0niz approved these changes

2024-02-20 15:16 UTC, merged