MIL-80 Второй этап админки
Studio-Yandex-Practicum/lizaalert_backend pull request #368
Opened 2024-02-17 17:20 UTC by mr-shifty

2024-02-19 11:51 UTC, cosmofactory requested changes

2024-02-19 11:51 UTC, cosmofactory commented on src/lizaalert/homeworks/admin.py
> +
```suggestion
    list_select_related = ("subscription", "user",)
```

2024-02-19 11:51 UTC, cosmofactory commented on src/lizaalert/homeworks/admin.py
> +    def get_queryset(self, request):
Добавь докстринг для будущих поколений, что мы тут делаем и почему

2024-02-19 11:51 UTC, cosmofactory commented on src/lizaalert/homeworks/admin.py
> +
Добавим пользователя в select_related

2024-02-19 11:51 UTC, cosmofactory commented on src/lizaalert/homeworks/admin.py
> +        if obj is not None and not request.user.is_superuser:
```suggestion
        if obj and not request.user.is_superuser:
```

2024-02-20 14:29 UTC, cosmofactory requested changes

2024-02-20 14:29 UTC, cosmofactory commented on src/lizaalert/homeworks/admin.py
> +        super().save_model(request, obj, form, change)
А зачем этот код?
Получается, что при создании дз мы назначаем создателя дз ревьюером.

2024-02-20 14:30 UTC, cosmofactory requested changes

2024-02-20 14:30 UTC, cosmofactory commented on src/lizaalert/homeworks/admin.py
> +        """Получить запрос к базе данных."""
```suggestion
        """
        Получить запрос к базе данных.
        
        Если пользователь имеет статус суперпользователя, то он видит все домашние задания.
        Если пользователь обычный администратор, то он видит только те домашние задания, 
         ревьюером которых является.
        """
```

2024-02-20 14:48 UTC, Di0niz requested changes

2024-02-20 14:48 UTC, Di0niz commented on src/lizaalert/homeworks/admin.py
>      list_select_related = ("subscription",)
нужно еще добавить пользователя

2024-02-20 14:48 UTC, Di0niz commented on src/lizaalert/homeworks/admin.py
> +        return False
лучше добавить файл с permission

2024-02-20 14:48 UTC, Di0niz commented on src/lizaalert/homeworks/admin.py
> +        return False
по аналогии с https://www.django-rest-framework.org/api-guide/permissions/

2024-02-20 16:27 UTC, cosmofactory commented on src/lizaalert/homeworks/admin.py
>      list_select_related = ("subscription",)
у нас пользователь из subscription берется

2024-02-22 09:46 UTC, cosmofactory commented on src/lizaalert/homeworks/permissions.py
> +class IsAuthenticated(BasePermission):
```suggestion
class IsReviewerOrSuperUser(BasePermission):
```

2024-02-22 09:46 UTC, cosmofactory commented on src/lizaalert/homeworks/permissions.py
> +class IsAuthenticated(BasePermission):
Мы же не проверяем, аутентифицирован он или нет. Мы проверям другое, так что название должно это отражать

2024-02-22 20:01 UTC, Di0niz requested changes

2024-02-22 20:01 UTC, Di0niz commented on src/lizaalert/homeworks/admin.py
>      list_select_related = ("subscription",)
```suggestion
    list_select_related = ("subscription__user",)
```

2024-02-22 20:01 UTC, Di0niz commented on src/lizaalert/homeworks/permissions.py
> +    def has_delete_permission(self, request, obj=None):
у кастомных пермишнов может быть только два метода

.has_permission(self, request, view)
.has_object_permission(self, request, view, obj)

2024-02-22 20:01 UTC, Di0niz commented on src/pyproject.toml
> +pyenchant = "^3.2.2"
проверка синтаксиса есть в браузере, давайте на сервер ничего дополнительного не устанавливать

```suggestion
```

2024-02-26 11:09 UTC, cosmofactory approved these changes

2024-02-26 17:25 UTC, Di0niz requested changes
перенеси код из has_permission в has_object_permission

2024-02-26 17:25 UTC, Di0niz commented on src/lizaalert/homeworks/admin.py
> +        fields = "__all__"
нужно явно указать перечень полей

2024-02-26 17:25 UTC, Di0niz commented on src/lizaalert/homeworks/permissions.py
> +    def has_permission(self, request, obj=None):
ожидается другая сигнатура функций

    def has_permission(self, request, view):

2024-02-26 17:25 UTC, Di0niz commented on src/lizaalert/homeworks/permissions.py
> +    def has_object_permission(self, request, view, obj=None):
def has_object_permission(self, request, view, obj):

2024-03-11 09:54 UTC, Di0niz requested changes

2024-03-11 09:54 UTC, Di0niz commented on src/lizaalert/homeworks/admin.py
> +            "text": TinyMCE(attrs={"cols": 80, "rows": 30}),
высота с 30 символов - это много, давай оставим  10

```suggestion
            "text": TinyMCE(attrs={"cols": 80, "rows": 10}),
```

2024-03-11 09:54 UTC, Di0niz commented on src/lizaalert/settings/urls.py
> +    path("tinymce/", include("tinymce.urls")),
это поле для админки, давай уберем в ручку /admin/tinemce/

2024-03-11 09:54 UTC, Di0niz commented on src/lizaalert/homeworks/admin.py
> +        pass
не очень понятно как эти permission работают

у админки есть 4 метода для работы с разрешениями:

            'add': self.has_add_permission(request),
            'change': self.has_change_permission(request),
            'delete': self.has_delete_permission(request),
            'view': self.has_view_permission(request),

2024-03-11 10:01 UTC, Di0niz approved these changes

2024-03-11 10:02 UTC, merged