MIL-89 Добавить валидацию id во вьюхи приложения courses
Studio-Yandex-Practicum/lizaalert_backend pull request #373
Opened 2024-02-19 12:46 UTC by cosmofactory

2024-02-19 13:12 UTC, ilin-art approved these changes

2024-02-20 10:07 UTC, Di0niz requested changes

2024-02-20 10:07 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +            course = validate_id(Course, id=course_id)
здесь используется как get_object,  а функция называется validate_id

2024-02-20 10:07 UTC, Di0niz commented on src/lizaalert/courses/views.py
> +            course = validate_id(Course, id=course_id)
если объект не найден, то лучше использовать средства drf

https://stackoverflow.com/questions/42032668/how-do-you-return-404-when-resource-is-not-found-in-django-rest-framework

2024-02-20 13:20 UTC, cosmofactory commented on src/lizaalert/courses/views.py
> +            course = validate_id(Course, id=course_id)
Имя поменял, но мы и так используем средства drf если объект не найден. 
Смысл этой функции в том, что если нам передали невальдный запрос, то показать, что запрос плохой

2024-02-20 13:34 UTC, Di0niz requested changes

2024-02-20 13:34 UTC, Di0niz commented on src/lizaalert/courses/utils.py
```
class BadRequestException(BaseBadRequestException):
      detail = "Invalid value"

 ```

2024-02-20 13:34 UTC, Di0niz commented on src/lizaalert/courses/utils.py
> +        raise BadRequestException({"detail": message})
```suggestion
def get_object(model, **kwargs):
    """Проверить корректность введенного id."""
    try:
        return get_object_or_404(model, **kwargs)
    except ValueError:
        raise BadRequestException()
```

2024-02-20 14:43 UTC, Di0niz approved these changes

2024-02-20 14:59 UTC, merged