MIL-94 Модель и приложение вебинара
Studio-Yandex-Practicum/lizaalert_backend pull request #379
Opened 2024-02-21 16:51 UTC by cosmofactory

2024-02-21 18:51 UTC, Di0niz requested changes

2024-02-21 18:51 UTC, Di0niz commented on src/lizaalert/webinars/models.py
> +    subscription = models.ForeignKey("courses.Subscription", on_delete=models.CASCADE, verbose_name="Подписка")
здесь ссылка на когорту

2024-02-21 18:51 UTC, Di0niz commented on src/lizaalert/webinars/models.py
> +
нужно еще добавить
- description - описание вебинара
- ссылка на видео запись
- описание записи вебинара (маркдоун, будем хранить расшифровку)

2024-02-21 18:51 UTC, Di0niz commented on src/lizaalert/webinars/models.py
> +
нужно еще добавить
- description - описание вебинара
- ссылка на видео запись
- описание записи вебинара (маркдоун, будем хранить расшифровку)

2024-02-22 05:33 UTC, Leontiev93 commented on src/lizaalert/webinars/models.py
> +    link = models.CharField(verbose_name="Ссылка на вебинар", max_length=400)
Возможно тут стоит использовать 
URLField

2024-02-22 06:35 UTC, Di0niz approved these changes

2024-02-22 09:40 UTC, merged