MIL-98 Добавить дату начала в ручку courses/id/enroll
Studio-Yandex-Practicum/lizaalert_backend pull request #384
Opened 2024-02-22 18:08 UTC by cosmofactory

2024-02-22 18:27 UTC, Leontiev93 approved these changes

2024-02-22 19:45 UTC, Di0niz requested changes

2024-02-22 19:45 UTC, Di0niz commented on src/lizaalert/courses/serializers.py
>          return subscription.status
здесь лучше убедиться что подписка есть и когорта заполнена

2024-02-22 19:45 UTC, Di0niz commented on src/lizaalert/courses/serializers.py
> +        return None
здесь нужно убедиться что подписка и когорта заполнена

2024-02-22 19:45 UTC, Di0niz commented on src/lizaalert/courses/serializers.py
> +        return None
еще нужно добавить теста, на то что получаешь дату в правильном формате

2024-02-26 17:17 UTC, Di0niz approved these changes

2024-02-26 17:38 UTC, merged