MIL-103 Добавить модель направлений для курсов
Studio-Yandex-Practicum/lizaalert_backend pull request #396
Opened 2024-02-26 19:54 UTC by Leontiev93

2024-02-28 07:25 UTC, Di0niz requested changes

2024-02-28 07:25 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +class DirectionInline(admin.StackedInline):
direction - как направление пути
замени на division

2024-02-28 07:25 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +    list_display = ("title", "author", "created_at", "updated_at", "courses")
добавь list related  для уменьшения повторных запросов

2024-02-28 07:25 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        return list(obj.course_set.all())
добавь prefetch для курсов, явно укажи те поля, которые будешь отображать пользователю

2024-02-28 07:25 UTC, Di0niz commented on src/lizaalert/courses/migrations/0028_auto_20240226_2234.py
> +class Migration(migrations.Migration):
одинаковые миграция нужно схлопнуть

2024-02-28 07:25 UTC, Di0niz commented on src/lizaalert/courses/models.py
> +        return self.title
нужно отображать id 

<Division id: title>

2024-02-28 12:10 UTC, cosmofactory commented on src/lizaalert/courses/models.py
> +    direction = models.ForeignKey(
А какой смысл нам усложнять и связывать Knowledge с Направлением? 

Курс дает какое то умение, из курса есть ссылка на умение. Не вижу необходимости привязывать умения к направлению.

2024-02-28 20:33 UTC, Leontiev93 commented on src/lizaalert/courses/admin.py
> +class DirectionInline(admin.StackedInline):
Исправлено !

2024-02-28 20:42 UTC, Leontiev93 commented on src/lizaalert/courses/models.py
> +    direction = models.ForeignKey(
отправил в бейдж

2024-02-28 20:42 UTC, Leontiev93 commented on src/lizaalert/courses/models.py
> +        return self.title
удалил def __str__

2024-03-03 13:07 UTC, cosmofactory approved these changes

2024-03-11 10:03 UTC, Di0niz requested changes

2024-03-11 10:03 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +    list_display = ("title", "author", "created_at", "updated_at")
magic-comma лучше оставить, чтобы не было лишних изменений

2024-03-11 10:03 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +    list_display = ("title", "author", "created_at", "updated_at")
оставь только udpdate_dt

2024-03-11 10:03 UTC, Di0niz commented on src/lizaalert/courses/admin.py
> +        return list(obj.course_set.all().values_list("title", flat=True))
для получения courses должен быть prefetch

2024-03-11 18:26 UTC, Leontiev93 commented on src/lizaalert/courses/admin.py
> +    list_display = ("title", "author", "created_at", "updated_at")
list_display = ("title", "author",  "updated_at",) Если я правильно понял то нужно было вот так сделать

2024-03-13 09:52 UTC, Di0niz approved these changes

2024-03-13 10:07 UTC, merged