Исправления бага homework
Studio-Yandex-Practicum/lizaalert_backend pull request #405
Opened 2024-03-04 19:57 UTC by Leontiev93

2024-03-04 20:09 UTC, cosmofactory requested changes
Во вьюхе мы 4 раза ходим в базу, чтобы получить одну домашку. 
При этом, если по какой то причине у нас станет две домашних работы, нам все равно вернёт 500.
В 22й строке переделай queryset, чтобы возвращал нужную нам работу, желательно за один запрос.

2024-03-05 05:13 UTC, Leontiev93 commented on src/lizaalert/homeworks/views.py
>              instance = get_object_or_404(Homework, **kwargs)
```
 try:
            instance = get_object_or_404(Homework, lesson_id=kwargs["lesson_id"], subscription_id=get_object_or_404(
                Subscription, user=request.user, course=get_object_or_404(Course, chapters__lessons=kwargs["lesson_id"])
            ) )
```

2024-03-05 19:21 UTC, cosmofactory approved these changes

2024-03-05 19:21 UTC, cosmofactory commented on src/lizaalert/courses/views.py
> +
А зачем тут исправление

2024-03-05 19:28 UTC, merged