MIL-112 Bugfix, не создавать когорту с датай начала раньше конца
Studio-Yandex-Practicum/lizaalert_backend pull request #412
Opened 2024-03-11 16:29 UTC by cosmofactory

2024-03-12 19:37 UTC, Leontiev93 approved these changes
Круто сделано !

2024-03-13 09:55 UTC, Di0niz requested changes

2024-03-13 09:55 UTC, Di0niz commented on src/lizaalert/courses/forms.py
> +            case CohortData(start_date, end_date, max_students) if all((start_date, end_date, max_students)):
количество студентов может быть неорганичено

2024-03-13 10:16 UTC, Di0niz approved these changes

2024-03-13 10:16 UTC, merged